Exiled-Team/EXILED

EXILED_Events/EXILED_Events.csproj
EXILED_Events/EventArgs.cs
EXILED_Events/Events.cs
EXILED_Events/Patches/GameConsoleQueryOverride.cs
EXILED_Events/Patches/ProcessGameConsoleQueryOverride.cs
EXILED_Events/Patches/ServerCommandPatch.cs

- Pretty straight forward, uses the `.command` kind of commands you send through the client's console.
* Command: the command from the player. Can be changed... in case anyone needs to for any particular reason.
* ReturnMessage: the message that will be returned. Defaults to "Command not found.", hope people change it or else I'll be mad.
* Color: the color of the message. Looks fairly cool and definitely better than Smod2's.
* Encrypted: bool, can't be changed, mainly for 2FA and alike, shouldn't matter since it will get interrupted if you're in online_mode but just in case.
Basically hooks into the RA command as SERVER CONSOLE with full perms.

The Command™ Pull Request

---

EXILED.sln
EXILED_Events/EXILED_Events.csproj
EXILED_Events/Events/EventArgs.cs
EXILED_Events/Events/ServerEvents.cs
EXILED_Events/Patches/SetGroupEvent.cs
EXILED_Events/Plugin.cs
EXILED_Main/Extensions/CassieExtensions.cs

Added SetGroupEvent

---

EXILED_Events/EXILED_Events.csproj
EXILED_Events/Events/EventArgs.cs
EXILED_Events/Events/PlayerEvents.cs
EXILED_Events/Patches/FemurEnterEvent.cs
EXILED_Events/Plugin.cs

Added FemurEnterEvent

---

EXILED_Events/EXILED_Events.csproj
EXILED_Events/Events/MapEvents.cs
EXILED_Events/Patches/WarheadDetonationPatch.cs

Added Warhead Detonation Event

---

EXILED_Main/Extensions/PlayerExtensions.cs

best pr ever lol

---

EXILED_Events/Patches/PreAuthEventPatch.cs

Fixing broken ip ban

---

EXILED_Events/Events/PlayerEvents.cs
EXILED_Events/Patches/CallCmdSetUnicOverride.cs
EXILED_Main/ApiObjects/AmmoType.cs
EXILED_Main/EXILED_Main.csproj
EXILED_Main/Extensions/PlayerExtensions.cs

Added: **Mute**, **Unmute**, **IsMuted**, **IntercomMute**, **IntercomUnmute**, **IsIntercomMuted**, **GetGodMode**, **SetGodMode**, **AddHealth**, **GetMaxHealth**, **GetAdrenalineHealth**, **SetAdrenalineHealth**, **AddAdrenalineHealth**, **GetMaxAdrenalineHealth**, **IsReloading**, **IsZooming**, **SetAmmo**, **GetAmmo**, **KickPlayer**

Added a lot of player's extensions

---

EXILED_Events/EventHandlers.cs
EXILED_Events/Events/EventArgs.cs
EXILED_Events/Events/MapEvents.cs
EXILED_Events/Events/PlayerEvents.cs
EXILED_Events/Events/ServerEvents.cs
EXILED_Events/Patches/RespawnEvent.cs
EXILED_Events/Patches/WaitingForPlayersEvent.cs
EXILED_Events/Plugin.cs
EXILED_Events/ReloadCommandHandler.cs
EXILED_Installer/Program.cs
EXILED_Main/Extensions/MapExtensions.cs
EXILED_Main/Extensions/PlayerExtensions.cs
EXILED_Main/Extensions/Scp914Extensions.cs
EXILED_Main/PluginManager.cs

- Added **GetIntakeBooth**, **GetOutputBooth** SCP914 extension
- Added **IsHost**, **HideTag**, **ShowTag** Player extensions
- Added **Rooms** Map property
- Fixed **GetCurrentRoom** Player extension, the room list was always empty
- Replaced a lot of "old" code with extensions
- Changed **DeadPlayer** from GameObjects list to ReferenceHubs list
- Cleaned up a lot of code (mainly spacing)

Added extensions and a lot of code cleanup

---

EXILED_Main/Extensions/Scp079.cs

- Added **Scp079** extensions: **GetLevels**, **SetLevels**, **GetAbilities**, **SetAbilities**.
- Fixed **SetMaxEnergy**, will now set the max energy permanently.

Additions and fixes

---

EXILED_Events/EventHandlers.cs
EXILED_Main/Extensions/Map.cs

Add Map.Doors that returns a List of all doors in the game.

Add Doors in Map Extension

---

EXILED_Main/ApiObjects/GlobalBadge.cs
EXILED_Main/Extensions/Player.cs

Added GetGlobalBadge method to Player extension to return a couple of global badge informations or null if the player don't have any global badge.

Add GetGlobalBadge to Player extension

---

EXILED_Events/EXILED_Events.csproj
EXILED_Events/Events/EventArgs.cs
EXILED_Events/Events/MapEvents.cs
EXILED_Events/Events/PlayerEvents.cs
EXILED_Events/ExiledVersion.cs
EXILED_Events/Patches/CancelMedicalItemEvent.cs
EXILED_Events/Patches/DoubleSpawnEventFix.cs
EXILED_Events/Patches/PlayerInteractEvent.cs
EXILED_Events/Patches/PlayerSpawnEvent.cs
EXILED_Events/Patches/UseMedicalItemEvent.cs
EXILED_Events/Patches/WarheadEvents.cs
EXILED_Events/Plugin.cs
EXILED_Main/Extensions/Map.cs

- Added **ActivatedGenerators** Map **property**.
- Added **TurnOffAllLights** Map **method**.
- Added **CancelMedicalItemEvent** and **PlayerInteractEvent** Player events.
- Added **Cooldown** property to **UseMedicalItemEvent**.
- Added **CancelMedicalEventPatchDisable**.
- Added **Player** property to **WarheadStartEvent**.
- Overloaded **==**, **!=**, **>**, **<**, **>=**, **<=** operators of **ExiledVersion** class.
- Added **ToString()** to the **ExiledVersion** class.
- Moved and renamed **DoubleSpawnEventFix** to its own class.

Added events, extensions and methods

---

EXILED_Events/EventHandlers.cs
EXILED_Events/Events/PlayerEvents.cs
EXILED_Events/Events/ServerEvents.cs
EXILED_Events/Patches/CheckRoundEndEvent.cs
EXILED_Events/Patches/DoorInteractionEvent.cs
EXILED_Events/Patches/PlayerSpawnEvent.cs
EXILED_Events/Patches/PocketDimEscapedEvent.cs
EXILED_Events/Plugin.cs
EXILED_Events/ReloadCommandHandler.cs
EXILED_Installer/Program.cs
EXILED_Main/ApiObjects/GlobalBadge.cs
EXILED_Main/Extensions/Map.cs
EXILED_Main/Extensions/Player.cs
EXILED_Main/MainLoader.cs
EXILED_Main/Plugin.cs
EXILED_Main/PluginManager.cs
EXILED_Permissions/Extensions.cs
EXILED_Permissions/Plugin.cs

- Added **AppDataDirectory**, **PluginsDirectory**, **ExiledDirectory**, **DependenciesDirectory**, **LoadedDependenciesDirectory**, **ConfigsPath**, **LogsPath** Properties.
- Added **reloadconfigs** command, to reload **plugin configs**.
- General **code cleanup**.
- Fixed a bug that would've throwed exceptions, if a server owner or a server moderator, had executed two or more commands in rapid succession.

 Added properties, command, bug fixes and code cleanup

---

EXILED_Events/EXILED_Events.csproj
EXILED_Events/Events/EventArgs.cs
EXILED_Events/Events/MapEvents.cs
EXILED_Events/Events/PlayerEvents.cs
EXILED_Events/Patches/PlaceBloodEvent.cs
EXILED_Events/Patches/PlaceDecalEvent.cs
EXILED_Events/Patches/UsedMedicalItem.cs
EXILED_Events/Plugin.cs
EXILED_Main/Extensions/Map.cs
EXILED_Main/Extensions/Player.cs

- Added **PlaceBloodEvent**, **PlaceDecalEvent** Map events.
- Added **UsedMedicalItemEvent** Player event.
- Changed **GetHubs** to actually reflect their **return types**.
- Added **exiled_remove_blood_placement** to Enable/Disable **blood** in the server.

Added events

---

EXILED_Events/Patches/GhostmodePatch.cs

Fixed 939 able to see ghostmode players

Fixed ghostmode with 939

---

EXILED_Main/Extensions/Item.cs
EXILED_Main/Extensions/Player.cs

- Added new Extensions for ItemTypes.
- Added new health-related extensions for ReferenceHubs.
- Added a maybe unnecessary bool for ReferenceHubs, but might make things simpler overall.

New extensions

---

EXILED_Main/Extensions/Player.cs

Added DropItem and RemoveItem methods in Player Extension.

Add DropItem(item) and RemoveItem(item)

---

EXILED_Main/Extensions/Map.cs
EXILED_Main/Extensions/Player.cs

Easier and more intuitive access to Round-lock, Lobby-lock & Friendly-fire booleans.

Roundlock, Lobbylock, FriendlyFire variables & fix AddHealth

---

EXILED_Events/EXILED_Events.csproj
EXILED_Events/Patches/CcmAnnoyingLoadFix.cs

```cs
if (base.isServer)
{
CharacterClassManager.OnlineMode = ConfigFile.ServerConfig.GetBool("online_mode", true);
ReservedSlot.Reload();
MuteHandler.Reload();
WhiteList.Reload();
}
```
to: 
```cs
if (base.isLocalPlayer)
{
CharacterClassManager.OnlineMode = ConfigFile.ServerConfig.GetBool("online_mode", true);
ReservedSlot.Reload();
MuteHandler.Reload();
WhiteList.Reload();
}
```

Annoying load fix from CCM

---

EXILED_Events/Events/MapEvents.cs

Made InvokeLockerInteract and InvokeGeneratorUnlock events public so we can call them from our patches

Changing accessibility level

---

Directory.Build.props
EXILED_Events/EXILED_Events.csproj
EXILED_Idler/EXILED_Idler.csproj
EXILED_Main/EXILED_Main.csproj
EXILED_Permissions/EXILED_Permissions.csproj

Finally sort out references to not be user specififc, keep in mind you need `EXILED_References` enviroment variable pointing to references directory (`D:\EXILED\SCPSL_Data\Managed` in my case)

Sort out references

---

.gitignore
EXILED_Main/ApiObjects/Side.cs
EXILED_Main/EXILED_Main.csproj
EXILED_Main/Extensions/Map.cs
EXILED_Main/Extensions/Player.cs

Because RSC made literally 0 sense, so I made a "Side" enum.

Better "Team" Enum

---

EXILED_Events/Patches/PlayerJoinEvent.cs
EXILED_Events/Patches/PlayerLeaveEvent.cs
EXILED_Events/Patches/RoundRestartEvent.cs
EXILED_Events/Plugin.cs
EXILED_Main/Log.cs

Remove Exiled2Multiadmin and Change LOGTYPE to ConsoleColor

---

GettingStarted.md

The title says it all.
I did this because it wasn't correct anymore.
kloveyoujoker.

Updated GettingStarted to the latest version of Exiled.

---

EXILED_Events/EXILED_Events.csproj
EXILED_Events/Events/EventArgs.cs
EXILED_Events/Events/ServerEvents.cs
EXILED_Events/Patches/DoorInteractionEvent.cs
EXILED_Events/Patches/LocalReportEvent.cs
EXILED_Events/Plugin.cs

In version 10.0.0, it's now possible to send a local report to the server 
maintainers. I created an event that handles it.

[Enhancement] LocalReportEvent

---

Exiled.API/Extensions/Role.cs
Exiled.API/Features/Player.cs

Added methods to get a RoleType's Color and more ways to access a Role/Team's Side

RoleColor & GetSide accesibility

---

Exiled.Patcher/Patcher.cs

Some of the code wasn't really necessary, and I added some credits.
I might add some docs to docx in the future though.

Exiled.Patcher Changes - Remove some redundant code, added credits.

---

GettingStarted.md

I fixed a lot of spelling mistakes.

Kade can't spell dynamic

---

Exiled.Events/Patches/Events/Scp079/Interacting.cs

And it was broken in only one line!

079 can only open doors and trigger tesla

---

Exiled.Events/EventArgs/SendingConsoleCommandEventArgs.cs
Exiled.Events/Extensions/Event.cs
Exiled.Events/Patches/Events/Server/SendingConsoleCommand.cs

SendingConsoleCommand now works with the maingame command system

---

GettingStarted.md

Updates it to a 2.0 workflow.
<3 you all.

GettingStarted Changes

---

GettingStarted.md

forgot to change the sample plugin to example plugin

GettingStarted Example Plugin Change

---

GettingStarted.md

Getting Started patch but im losing my sanity

---

Exiled.API/Features/Map.cs
Exiled.API/Features/Player.cs
Exiled.API/Features/Room.cs
Exiled.API/Features/Round.cs

Fix `Room.Zone` & `Round.EslapedTime`

---

Exiled.Loader/Loader.cs

- Possibility of loading a plugin with a private constructor.
- Bug fix for using exclusively static properties as initializers.
- Other cleaning of code from unnecessary things.

Loader improvement

---

Exiled.Loader/Loader.cs

Revert "Loader improvement"

---

Exiled.Events/Commands/Reload/Configs.cs
Exiled.Events/Commands/Reload/GamePlay.cs
Exiled.Events/Commands/Reload/RemoteAdmin.cs
Exiled.Events/Handlers/Server.cs

Changed the names of the reload events

---

Exiled.Events/EventArgs/GainingLevelEventArgs.cs
Exiled.Events/Patches/Events/Scp079/GainingLevel.cs
Exiled.Events/Patches/Events/Scp106/Containing.cs

Fixed the 079 level and the 106 containing event.

Fixed some events

---

.github/workflows/main.yml

I think this should solve the problem of using the same commit in PR.

Bump actions@checkout to v2.3.1

---

Exiled.Events/Patches/Events/Player/Shoot.cs

Fixed Damage from being ignored from ShotEventArgs.

Fix ShotEventArgs damage

---

Exiled.Example/Example.cs
Exiled.Example/Handlers/Server.cs

In hopes of stopping the numerous Leading Team console spam that users come across, I've changed the event where that line is called from OnEndingRound to OnRoundEnd.
I've also added an example of debug, info, and warn messages with comments to spread awareness of their existence to be used!

Example Modifications

---

Exiled.Events/Patches/Generic/GhostMode.cs

- Reworked GhostMode
- Fixed a bug that inverted Player.IsInvisible effect (All players were invisible to the "invisible" player and he was always visible to others)

[GhostMode] Rework and bugfix

---

Exiled.Permissions/Commands/Permissions/Add.cs
Exiled.Permissions/Commands/Permissions/Group/Remove.cs
Exiled.Permissions/Commands/Permissions/Remove.cs
Exiled.Permissions/Extensions/Permissions.cs
Exiled.Permissions/Features/Group.cs
Exiled.Permissions/permissions.yml
README.md

Added inheritance support for the permissions.
It works by adding the name of any groups to inherit from in the `Inheritance` list.

Added inheritance support for Exiled.Permissions

---

Exiled.Installer/CommandSettings.cs
Exiled.Installer/Program.cs
Exiled.Installer/Properties/PublishProfiles/FolderProfile.pubxml
Exiled.Installer/README.md

- Fix installer.
- Limit for versions (2.0.0 inclusive).
- Add some parameters.

Fix and improve installer

---

.github/workflows/installer.yml
Exiled.Installer/Program.cs

- Resolve required launch permissions from CI.
- Unpacking the target file to the correct location.

Fix installer

---

Exiled.Events/Patches/Events/Player/PreAuthenticating.cs

Fk me, i forgot to change 2 lines..

Real fix for user id in pre-auth event

---

Exiled.Updater/Exiled.Updater.csproj
Exiled.Updater/Updater.cs

- Fix mono bug preventing HttpClient from working properly.
- Some code cleanup.

HttpProxy bypass

---

Exiled.Events/Patches/Events/Player/EscapingAndFailingEscapePocketDimension.cs

We got `NullReferenceException` at the bottom of the method when trying to assign a player's position, but there was no check anywhere that it was a player, `Pickup` doesn't have a `PlayerMovementSync` component.
This solves https://github.com/galaxy119/EXILED/issues/198.

Fix NRE at PocketDimensionTeleport.OnTriggerEnter(Collider)

---

Exiled.Events/Patches/Events/Player/EscapingAndFailingEscapePocketDimension.cs

Optimization consists of one call to `Player::Get` for all events.

Optimize EscapingAndFailingEscapePocketDimension event

---

Exiled.Events/EventArgs/InteractingLockerEventArgs.cs
Exiled.Events/Patches/Events/Player/InteractingLocker.cs

I've updated the events and added some useful properties, also marked the conflicting properties as obsoleted so as not to break the existing plugins.

Update InteractingLocker event

---

.github/workflows/main.yml
EXILED.targets
Exiled/Exiled.nuspec

- Fixed license expression & removed packing into `.nupkg` file.
- Added `copyright` property.
- Added `repository` property.

Update the Exiled.nuspec file

---

Exiled.API/Enums/RoomType.cs
Exiled.API/Features/Map.cs
Exiled.API/Features/Room.cs

Gave the class Room a RoomType variable which is set in the constructor.
Added the Surface (Outside) as a room.
Created RoomType enum to define rooms.

Room Types

---

Exiled.Updater/Exiled.Updater.csproj
Exiled.Updater/LinuxPermission.cs
Exiled.Updater/Updater.cs
Exiled.Updater/VersionComparer.cs

- Fixed updater target version argument to installer
- Fixed updater version comparer
- Updater version bumped to 3.0.2

Updater fixes

---

Exiled.API/Features/Player.cs
Exiled.Bootstrap/Bootstrap.cs

This reverts commit 48d92fafba38d7f9e48dcbd44a3a73575a3fa4b2.

Revert "Not sure why where were errors for me but they were"

---

Exiled.Events/Patches/Events/Player/Died.cs

Same as #173, but for the died event.

Fix attacker in the player died event

---

Exiled.Installer/CommandSettings.cs

Prevents strange behavior from #213.

Checking for empty or null paths while processing arguments

---

Exiled.Events/Handlers/Player.cs
Exiled.Events/Patches/Events/Player/Hurting.cs

Fixed Died event on 079 not firing after recontainment and added Scp079Recontainment event

SCP-079 Death Fix

---

Exiled.Events/EventArgs/StartingSpeakerEventArgs.cs
Exiled.Events/EventArgs/StoppingSpeakerEventArgs.cs
Exiled.Events/Handlers/Scp079.cs
Exiled.Events/Patches/Events/Scp079/Interacting.cs

- Updated **InteractingTesla, InteractingDoor** Scp079 event to **2.x**
- Added **StartingSpeaker, StoppingSpeaker** Scp079 event

Update and added some scp079 events

---

Exiled.Events/Patches/Events/Player/EnteringPocketDimension.cs

Behavior won't change, just cleanup and optimization.

`Scp106PlayerScript::CallCmdMovePlayer` patch cleanup

---

Exiled.API/Features/Player.cs
Exiled.API/Features/Room.cs
Exiled.Events/EventArgs/StartingEventArgs.cs
Exiled.Events/Patches/Generic/StaminaUsagePatch.cs

Room.Doors property gets all doors in the room
Player.IsUsingStamina property allows disabling stamina for certain players

Added Room.Doors and Player.IsUsingStamina properties

---

Exiled.Events/Commands/Reload/Plugins.cs
Exiled.Loader/Loader.cs

I found out that the "rld plugins" command is not working correctly. Here is the fixed version

Fixed rld plugins command

---

Exiled.Permissions/Extensions/Permissions.cs

* use key only current player group

fix behavior with the default permission group

---

Exiled.Events/EventArgs/ChangingWarheadLeverStatusEventArgs.cs
Exiled.Events/Handlers/Player.cs
Exiled.Events/Patches/Events/Player/ChangingWarheadLeverStatus.cs

ChangingWarheadLeverStatusEventArgs class didnt have corresponding event

Implemented event for ChangingWarheadLeverStatusEventArgs

---

Exiled.Events/Commands/Show/Plugins.cs
Exiled.Events/Commands/Show/Show.cs
Exiled.Events/Commands/ShowPlugins.cs

This can be useful for finding conflicts among plugins or quickly showing installed plugins.

Added a new command to show installed plugins 

---

Exiled.API/Features/Player.cs

This should fix the issue with GetCurrentRoom returning new rooms.

Get current room fix

---

README.md

I think people should read the guide now. I swear if we have to simplify it more we're boutta go insane or else we can just post a 1 minute video or something idk anymore

Simplified README.md slightly

---

Exiled.Events/Commands/Reload/All.cs
Exiled.Events/Commands/Reload/Configs.cs
Exiled.Events/Commands/Reload/GamePlay.cs
Exiled.Events/Commands/Reload/Plugins.cs
Exiled.Events/Commands/Reload/Reload.cs
Exiled.Events/Commands/Reload/RemoteAdmin.cs

This just executes all of the subcommands and prints their responses for the reload command.

Add all subcommand to the reload command

---

Exiled.Events/EventArgs/ChangingIntercomMuteStatusEventArgs.cs
Exiled.Events/Handlers/Player.cs
Exiled.Events/Patches/Events/Player/ChangingIntercomMuteStatus.cs

* ChangingMutedStatus: Replaced "Status" (get) with "IsMuted" (get) (same functionality, better name)
* ChangingIntercomMutedStatus: Added, invoked when a person is muted/unmuted from the intercom.

ChangingMutedStatus & ChangingIntercomMutedStatus

---

Exiled.Events/EventArgs/SpawningItemEventArgs.cs
Exiled.Events/Handlers/Map.cs
Exiled.Events/Patches/Events/Map/SpawningItem.cs

* Map.SpawningItem
- ItemType Id (get, set): The Item ID to spawn.
- Vector3 Position (get, set): The position of the item being spawned
- Quaternion Rotation (get, set): The rotation of the item being spawned
- bool IsAllowed (get, set)

Adding Map.SpawningItem event

---

Exiled.API/Features/Room.cs

Room.LightsOff (bool): Gets a value indicating whether or not the lights in this room are currently flickered off.

Adding Room.LightsOff

---

README.md

This seemed a bit off and at the wrong point.

Move Note to correct line

---

Exiled.API/Features/Player.cs

* Added Player::DisableEffect\<T\>() to go along with Player::DisableAllEffects().

Adding Player::DisableEffect<T>

---

Exiled.Events/Patches/Events/Player/Shoot.cs

Fix headshots not working

---

Exiled.Events/Patches/Events/Player/Shoot.cs

oh uh forgot to use label

---

Exiled.API/Features/Cassie.cs

* `Cassie::IsSpeaking` - Returns true if cassie is currently playing an announcement

Adding Cassie::IsSpeaking

---

Exiled.Events/Patches/Events/Player/ChangingRole.cs

This should fix https://trello.com/c/Cb4Jpmr0/1853-stamina-bug

Set stamina to 100 on spawn

---

Exiled.API/Features/Scp096.cs

Reflect Vanilla 096 changes

---

Exiled.Events/EventArgs/ContainingEventArgs.cs
Exiled.Events/Patches/Events/Scp106/Containing.cs

Adding `Player buttonPresser` to the EventHandler for 106 Containment.

Adding buttonPresser to 106 containment handler

---

Exiled.API/Features/Respawn.cs

Adding `ForceWave(SpawnableTeamType team, bool playEffects = false)` that was lost in [PR 308](https://github.com/galaxy119/EXILED/pull/308)

ForceWave + Tickets APIs

---

Exiled.API/Features/Room.cs

`Room::SetLightIntensity(float intensity)` - Sets the intensity of the lights in the room. 0 = lights are off, 2 = lights are 2x brighter lights, etc

Adding Room::SetLightIntensity

---

Exiled.API/Features/Player.cs

It should be useful when you are doing something with player in the coroutine.

Added Player::IsConnected property

---

Exiled.API/Enums/DoorType.cs
Exiled.API/Features/Cassie.cs
Exiled.API/Features/Log.cs
Exiled.API/Features/Map.cs
Exiled.API/Features/Player.cs

* Doc stuff: as always
* Moving Player::GetCameraById to (static) Map::GetCameraById (having it as a non-static in the player class literally made no sense)
* Adding an overload to Player::SetCamera to take a camera object

Development docs & Miscellaneous API addition

---

Exiled.API/Features/Player.cs

Why didn't we have that before...

Some useful properties in Player API (IsHuman, IsScp)

---

Exiled.Events/EventArgs/InteractingElevatorEventArgs.cs

Considering Type will soon be obsolete, we should probably provide the actual lift lol

Adding InteractingElevatorEventArgs.Lift

---

Exiled.API/Features/Player.cs

* <s>`Player::GetActiveEffects()` (PlayerEffect[]) - Returns an array of active player effects</s>
* <s>`Player::EnableEffects(string[], float, bool)` (bool) - Enables a list of effects for duration, returns true if all successful</s>
* `Player::EffectActive<T>()` (bool) - Returns if given type is active
* `Player::ChangeEffectIntensity<T>(byte)` (void) - Changes the effect intensity
* `Player::ChangeEffectIntensity(string, byte)` (void) - Changes the effect intensity
* `Player::GetEffectIntensity<T>()` (byte)` - Returns effect intensity
* Modified: `Player::DisableAllEffects` to only call disabled on the enabled effects
(Apologies for like my 20th PR in the past week)

Adding and modifying methods for Player effects

---

Exiled.API/Features/Server.cs

Adding Server.IpAddress

---

Exiled.Events/Patches/Events/Player/Shoot.cs

fix shoot ac from maingame

---

Exiled.Events/EventArgs/SpawningRagdollEventArgs.cs
Exiled.Events/Patches/Events/Player/SpawningRagdoll.cs

This seems like the only efficient way to modify a Ragdoll velocity since HarmonyPatch cannot be stacked.

Configurable Velocity on SpawnRagdoll

---

Exiled.API/Enums/DoorType.cs
Exiled.API/Extensions/DoorTypeExtension.cs
Exiled.API/Extensions/String.cs
Exiled.API/Features/Server.cs

let me know if I broke something, first time committing to Exiled in a bit

Fixed door type stuff

---

Exiled.API/Features/Player.cs

Does exactly what it sounds like, searches the player's inventory and if the given item is found returns true. Otherwise false.
(but it actually works this time)

Added new method for Player, "HasItem".

---

Exiled.API/Features/Map.cs

this is a really important fix

Fixing everything

---

EXILED.props
Exiled.API/Features/Map.cs

Added Map.ChangeUnitColor()

---

Exiled.Events/EventArgs/DequippedMedicalItemEventArgs.cs
Exiled.Events/Events.cs
Exiled.Events/Handlers/Player.cs
Exiled.Events/Patches/Events/Player/DequippedMedicalItem.cs
Exiled.Events/Patches/Events/Player/UsedMedicalItem.cs

Isn't actually a bug, but will be merged into dev as well as dev-enhancement soon.

Medical events mess

---

Exiled.CreditTags/Commands/ShowCreditTag.cs
Exiled.CreditTags/Config.cs
Exiled.CreditTags/CreditTags.cs
Exiled.CreditTags/Enums/InfoSide.cs
Exiled.CreditTags/Enums/RankKind.cs
Exiled.CreditTags/Events/CreditsHandler.cs
Exiled.CreditTags/Features/Rank.cs
Exiled.CreditTags/Features/ThreadSafeRequest.cs

+ Added a player null check to ShowCreditTag command.
+ Slightly reworked the project structure.

General clean up and moved things around

---

.github/workflows/main.yml
.github/workflows/programs.yml
.github/workflows/push_nuget.yml
Exiled.CreditTags/CreditTags.cs
build.ps1

- Switching to using a build script
- Adds a CD

The Cooler CI & CD

---

Exiled.CreditTags/Config.cs
Exiled.CreditTags/CreditTags.cs
Exiled.CreditTags/Enums/InfoSide.cs

This image describes the reason

Remove the Both mode from InfoSide

---

EXILED.props
Exiled.Events/Patches/Events/Player/EnteringPocketDimension.cs
Exiled.Events/Patches/Events/Server/LocalReporting.cs
Exiled.Updater/Updater.cs

Ignore build errors references won't be updated until PRs are reviewed.

Mirror of PR into master to update game to 10.2.2

---

Exiled.API/Extensions/MirrorExtensions.cs

merge from https://github.com/sanyae2439/Exiled.MirrorExtensions

MirrorExtensions

---

Exiled.API/Extensions/Item.cs

This will save some code to a few plugins.

Adding GetDefaultDurability()

---

Exiled.CustomItems/Commands/Spawn.cs

Use customitems.spawn instead of customitems.list
Spawn isn't a List's command parent after all.

Added new permission

---

Exiled.API/Extensions/MirrorExtensions.cs
Exiled.API/Features/Map.cs
Exiled.CustomItems/Commands/List/List.cs
Exiled.CustomItems/CustomItems.cs
Exiled.Events/EventArgs/ChangingIntoGrenadeEventArgs.cs
Exiled.Events/EventArgs/ChangingRadioPresetEventArgs.cs
Exiled.Events/EventArgs/UsingRadioBatteryEventArgs.cs
Exiled.Events/Handlers/Player.cs
Exiled.Events/Patches/Events/Item/ChangingAttachments.cs
Exiled.Events/Patches/Events/Map/ChangingIntoGrenade.cs
Exiled.Events/Patches/Events/Player/ChangingRadioPreset.cs
Exiled.Events/Patches/Events/Player/EnteringPocketDimension.cs
Exiled.Events/Patches/Events/Player/PickingUpItem.cs
Exiled.Events/Patches/Events/Player/PreAuthenticating.cs
Exiled.Events/Patches/Events/Player/UsingRadioBattery.cs
Exiled.Events/Patches/Events/Player/Verified.cs
Exiled.Events/Patches/Events/Scp096/AddingTarget.cs
Exiled.Example/Events/MapHandler.cs
Exiled.Example/Events/PlayerHandler.cs
Exiled.Example/Example.cs
Exiled.Installer/Program.cs
Exiled.Loader/Loader.cs
Exiled.Updater/GHApi/Settings/GetReleasesSettings.cs
Exiled.Updater/Updater.cs

`[Exiled.Events]`
+ Added ChangingRadioPreset and UsingRadioBattery events.
+ Some clean up.

New events

---

Exiled.Events/Patches/Events/Scp096/ChargingPlayer.cs
Exiled.Events/Patches/Events/Scp096/TryingNotToCry.cs

This will also fix the ChargingPlayer event being called multiple times per player.

Change ChargingPlayer and TryingNotToCry into transpilers

---

Exiled.Events/Patches/Fixes/GrenadesFailToExplodeFix.cs

Fix grenades fail to explode

---

Exiled.Events/Patches/Events/Scp079/ChangingCamera.cs
Exiled.Events/Patches/Events/Scp079/Interacting.cs

+ Fixed the logic of IsAllowed for Interacting patch (from `<` to `<=`).

Converted ChangingCamera into a transpiler

---

Exiled.Example/Example.cs

- Deleted the private constructor.
- Moved down ``base.OnEnabled()`` and ``base.OnDisabled()``.

Cleaning a little bit the example plugin

---

Exiled.API/Extensions/String.cs
Exiled.CreditTags/CreditTags.cs

Anonymize userid's sent to credits API.

---

Exiled.API/Enums/DoorType.cs

Fixed a typo

---

Exiled.Events/Config.cs

* add Description
* set default

mini fix ShouldReloadConfigsAtRoundRestart config

---

Exiled.Events/Patches/Fixes/AntiCheatTriggerByR3WithCustomScale.cs
Exiled.Events/Patches/Generic/AntiCheatTriggerByR1WithTriggerCollider.cs
Exiled.Events/Patches/Generic/AntiCheatTriggerByS7WithTriggerCollider_AntiFly.cs
Exiled.Events/Patches/Generic/AntiCheatTriggerByS7WithTriggerCollider_CheckAnticheatSafe.cs
Exiled.Events/Patches/Generic/AntiCheatTriggerByS7WithTriggerCollider_CheckIfGrounded.cs

Trello card: https://trello.com/c/47yas0z5

Anti Cheat Likes Custom Colliders

---

Exiled.API/Features/Player.cs

This is useful to count the items of a certain ItemType a player has in his inventory.

Player.CountItem(ItemType)

---

Exiled.API/Features/Player.cs

Add Player:Ping

---

Exiled.CustomItems/Commands/Give.cs

The title explains most of this PR. I also added a check to exclude giving cuffed players custom items.

Allow custom items to be given to all players at once

---

Exiled.API/Features/Player.cs

I don't know how to rename it, I think it might be useful tho.

Added NetworkforceStopInputs

---

Exiled.Events/EventArgs/UsingRadioBatteryEventArgs.cs
Exiled.Events/Patches/Events/Player/UsingRadioBattery.cs

Adds Radio instance to Player::UsingRadioBattery

---

Exiled.CustomItems/API/Extensions.cs
Exiled.CustomItems/API/Features/Vector.cs
Exiled.CustomItems/API/Spawn/DynamicSpawnPoint.cs
Exiled.CustomItems/API/Spawn/SpawnPoint.cs
Exiled.CustomItems/API/Spawn/StaticSpawnPoint.cs
Exiled.Example/Config.cs
Exiled.Loader/Exiled.Loader.csproj
Exiled.Loader/Features/Configs/CustomConverters/VectorsConverter.cs
Exiled.Loader/Loader.cs

+ Unity Vector2, Vector3 and Vector4 can now be converted into configs and vice versa.
+ Exiled.CustomItems.API.Features.Vector has been deprecated.

Vector2, Vector3 and Vector4 config converter

---

Exiled.API/Features/Map.cs

Thanks to Steven for the idea.

Adding Exiled.API.Features.Map.Seed

---

Exiled.Events/EventArgs/ChangingMicroHIDStateEventArgs.cs
Exiled.Events/EventArgs/UsingMicroHIDEnergyEventArgs.cs
Exiled.Events/Patches/Events/Player/ChangingMicroHIDState.cs
Exiled.Events/Patches/Events/Player/UsingMicroHIDEnergy.cs

The titles says all, I think. I'm tinybrain I know, but everyone makes mistakes.

Fixed UsingMicroHIDEnergy being called each frame + added MicroHID instances to both events

---

Exiled.API/Features/Map.cs
Exiled.Events/Patches/Events/Map/DamagingWindow.cs

After a whole day with headache learning .NET Framework based IL I made my first transpiler 😎

Converted DamagingWindow into a transpiler

---

Exiled.API/Features/Player.cs

Added the ForceCuff (RA) check in Player.IsCuffed bool

Added ForceCuff check in Player.IsCuffed

---

Exiled.Events/EventArgs/LockdowningEventArgs.cs
Exiled.Events/EventArgs/LockingDownEventArgs.cs
Exiled.Events/Handlers/Scp079.cs
Exiled.Events/Patches/Events/Scp079/Interacting.cs

Adds a SCP-079 Lockdown event (when scp-079 turns off the lights in room and locks the doors in it)

Add LockingDown Event

---

Exiled.Events/EventArgs/ChangedRoleEventArgs.cs
Exiled.Events/Handlers/Player.cs
Exiled.Events/Patches/Events/Player/ChangingRole.cs

It's wrong and it was a pain in the ass for me

Fixed description of Shot event

---

Exiled.API/Extensions/UserGroupExtensions.cs
Exiled.Events/EventArgs/ChangedRoleEventArgs.cs
Exiled.Events/Patches/Events/Player/ChangingRole.cs
README.md

It didn't want to let me commit to my old PR so I had to remake this?

Add GetValue() to UserGroupExtensions

---

Exiled.API/Features/Player.cs

Those're my extensions that I'm currently using to avoid filling the code with for / foreach loops.
May they be useful?

Added some variants of Player.AddItem() method

---

.github/workflows/beta.yml
Exiled.CustomItems/API/Extensions.cs
Exiled.Events/EventArgs/ChangedRoleEventArgs.cs
Exiled.Events/Patches/Events/Player/ChangingRole.cs
README.md

"079_SECONDARY" is incorrect, should be "079_SECOND"

Fix typo in the returned door name

---

Exiled.API/Features/Room.cs
Exiled.Events/EventArgs/ChangedRoleEventArgs.cs
Exiled.Events/Patches/Events/Player/ChangingRole.cs
README.md

Adds an IEnumerable which adds the room's cameras to it.

Add Cameras IEnumerable to Room

---

Exiled.Events/Patches/Events/Player/SpawningRagdoll.cs

ev.Owner is currently broken, both ev.Owner and ev.Killer are the same player. This fixes it.

Fixing ev.Owner

---

Exiled.API/Interfaces/IPlugin.cs

Fix XML docs for InternalTranslation

---

Exiled.API/Extensions/MirrorExtensions.cs

Fix NRE for PlayCassieAnnouncement

---

Exiled.Events/Commands/Reload/Configs.cs
Exiled.Events/Commands/Reload/Translations.cs

Reload plugin commands on config/translations reload

---

Exiled.CustomItems/API/Features/CustomItem.cs

Make CustomItems spawn where the player is after escaping

---

Exiled.Events/EventArgs/BanningEventArgs.cs

Reverts Exiled-Team/EXILED#584

Revert "Update BanningEventArgs.cs"

---

Exiled.API/Extensions/MirrorExtensions.cs

Updated for Mirror change.
(and add comments for SendFakeSyncObject)

Fix SendFakeSyncVar to maingame 11.x 

---

Exiled.Events/Patches/Fixes/DoubleMute.cs

Fix NetworkMute patch

---

Exiled.Events/Patches/Events/Player/TriggeringTesla.cs

Fix TriggeringTesla event

---

Exiled.Events/Patches/Events/Player/Banned.cs

Banned event AHHHHH

---

Exiled.Events/Patches/Fixes/WeaponAttachmentDesyncFix.cs

from Discord #bug-reports
Testing: done

Fix attachment desync

---

Exiled.Events/Patches/Events/Scp096/AddingTarget.cs

Fix SCP-096 AddTarget when multi targets

---

Exiled.Events/Patches/Events/Player/TriggeringTesla.cs

from Discord #bug-reports
testing with 2,3,4 players

Fix teslagate idle and IsTriggerable

---

Exiled.API/Extensions/MirrorExtensions.cs

Its not braeking changes.
testing: done.

Fix KeyNotFoundException whe use Enum values to SendFakeSyncVar()

---

Exiled.Events/Patches/Events/Player/ChangingMicroHIDState.cs

Reverts Exiled-Team/EXILED#615

Revert "ChangingMicroHidState Patch"

---

Exiled.Events/Config.cs

Mirror 11.0 maximum hume shield change.

Update Scp096 Max Hume

---

Exiled.Events/Patches/Events/Player/IntercomSpeaking.cs

Alright, I remembered to change the patching method. I don't know why it worked in my testing initially, but whatever. Should be actually working now.

Change IntercomSpeaking to transpiler 

---

Exiled.Events/Patches/Events/Player/Kicked.cs

Remove Patching Debug

---

Exiled.Events/Patches/Events/Server/RestartingRound.cs

Convert Restarting round prefix into transpiler

Convert RoundRestarting patch into transpiler

---

Exiled.Events/Patches/Events/Player/Handcuffing.cs

_Disarm and Release base-game commands are broken even without any patch._
**A NRE may occour while using those commands.**

Change Handcuff/Removing patches to transpilers

---

Exiled.API/Features/Room.cs

Added RoomColor and ResetRoomColor

RoomColor stuff

---

Exiled.API/Extensions/RoleExtensions.cs
Exiled.API/Features/Player.cs
Exiled.Events/Patches/Events/Warhead/Detonated.cs

Added Player::LeadingTeam and RoleExtensions::GetLeadingTeam(this Team team)

Added Player::LeadingTeam

---

Exiled.API/Enums/RoomType.cs
Exiled.API/Features/Room.cs

Add RoomType

---

Exiled.API/Features/Door.cs

Since there's a position property, I think it's

Added Door::Rotation

---

Exiled.API/Features/ShootingTarget.cs

I dont wanna talk about it, I tested it before I converted it from a switch to a dictionary.

Fix typo in binary

---

Exiled.Events/Patches/Events/Scp096/ChargingPlayer.cs

Updated damage values, now uses ev.Damage's getter

Update ChargingPlayer event

---

Exiled.API/Features/Player.cs
Exiled.CustomItems/Commands/List/List.cs

Now HasItem has support for Exiled Item.
Added DropHeldItem.

HasItem Rework and adding DropHeldItem

---

Exiled.API/Features/Cassie.cs

Mimics that of basegames "cassieclear" command

Cassie clear method

---

Exiled.Events/Patches/Events/Player/ChangingRole.cs
Exiled.Events/Patches/Generic/RoleChangedPatch.cs

No coroutines used, and items orders is fine.
and Fix items not being keep when escaping.

Better ChangingRole and Fix items not being keep when escaping

---

Exiled.Events/Patches/Events/Player/Destroying.cs

Reverts Exiled-Team/EXILED#808 (just a test)

Revert "Re-convert Destroying patch to transpiler"

---

Exiled.Events/Handlers/Internal/MapGenerated.cs

Fix default room

---

Exiled.Events/EventArgs/ExplodingGrenadeEventArgs.cs

I was annoyed by IsFrag, so now it has the Grenadetype in the ev

Exploding Grenade Type

---

Exiled.CustomRoles/API/Features/ActiveAbility.cs
Exiled.CustomRoles/API/Features/CustomRole.cs
Exiled.CustomRoles/Config.cs

I hope this first mine PR is okay)

Added translations for CustomRoles (like in CustomItems)

---

Exiled.Events/EventArgs/TogglingFlashlightEventArgs.cs
Exiled.Events/Handlers/Player.cs
Exiled.Events/Patches/Events/Player/TogglingFlashlight.cs

Useful for item customization or extra features.

Added TogglingFlashlight event

---

Exiled.Events/Patches/Events/Server/RoundEnd.cs

Fix LeadingTeam

---

Exiled.API/Features/Player.cs

Added `Player::ApplyRandomEffect`

---

Exiled.API/Features/Ragdoll.cs

Added `Ragdoll::Get`

---

Exiled.Events/Patches/Events/Player/Jumping.cs

Fixed Issue #863

---

Exiled.API/Features/Player.cs

Fixed Player.Handcuff being broken (Issue #868)

---

Exiled.API/Features/Map.cs
Exiled.API/Features/Room.cs
Exiled.Events/Handlers/Internal/MapGenerated.cs

Fixed Issue #826

---

Exiled.Events/Patches/Events/Player/SpawningRagdoll.cs

There are no errors. I'm using the dev branch version.
Patch works and it has been tested right now.

Re-enable SpawningRagdoll transpiler

---

Exiled.Events/Patches/Events/Player/Shooting.cs

Fixed Issue #873 and Joker's tinybrain.

Fixed Issue #873

---

Exiled.Events/Patches/Events/Player/Hurting.cs

> Burned effect multiplier is not being calculated
> Dying event is not triggered sometimes
> FriendlyFireFactor multiplier is not being calculated
> SpawnProtection factor is not being calculated
> Team check is not being calculated
> Godmode check is not being calculated
> Max value is not being calculated
> Spectator role check is not being calculated
> There's a possibile NRE
All solved.

Fixed Hurting patch logic

---

Exiled.Events/Patches/Events/Player/SpawningRagdoll.cs

Reverts Exiled-Team/EXILED#810

Revert "Re-enable SpawningRagdoll transpiler"

---

Exiled.API/Enums/DamageType.cs
Exiled.API/Features/DamageHandler.cs

This also includes the changes from #922 in a non-breaking way.

Handle damage type conversion more efficiently.

---

Exiled.Events/Patches/Events/Map/ExplodingFlashGrenade.cs

using a friendly fire check that actually works

Flashing fix

---

Exiled.Events/Patches/Events/Scp096/AddingTarget.cs

Waiting for Nao to have an aneurism

Make 096 not add rage time to targets while enraged to mimic base-game

---

Exiled.Events/EventArgs/InteractingScp330EventArgs.cs
Exiled.Events/EventArgs/PickingUpScp330EventArgs.cs
Exiled.Events/Handlers/Player.cs
Exiled.Events/Patches/Events/Scp330/InteractingScp330.cs
Exiled.Events/Patches/Events/Scp330/PickingUp330.cs

Technically the changes to the PickingUpScp330EventArgs aren't breaking changes, because the event that used them hasn't been implemented since halloween.

re-implement PickingUpScp330 and add new InteractingScp330 event.

---

Exiled.Events/EventArgs/TriggeringTeslaEventArgs.cs
Exiled.Events/Patches/Events/Player/TriggeringTesla.cs

- Add The Tesla
- Add The IdlingEffect

More args in TriggeringTeslaEvent

---

Exiled.API/Enums/GrenadeType.cs
Exiled.API/Extensions/CameraExtensions.cs
Exiled.API/Extensions/SpawnExtensions.cs
Exiled.API/Extensions/UserGroupExtensions.cs
Exiled.API/Features/Items/Scp330.cs
Exiled.API/Features/Map.cs
Exiled.API/Features/Player.cs
Exiled.API/Features/Ragdoll.cs
Exiled.API/Features/Scp914.cs
Exiled.API/Features/Server.cs
Exiled.CustomItems/API/Features/CustomItem.cs
Exiled.CustomRoles/API/Features/CustomAbility.cs
Exiled.CustomRoles/API/Features/CustomRole.cs
Exiled.Events/EventArgs/AddingTargetEventArgs.cs
Exiled.Events/EventArgs/ChangingCameraEventArgs.cs
Exiled.Events/EventArgs/EatenScp330EventArgs.cs
Exiled.Events/EventArgs/EatingScp330EventArgs.cs
Exiled.Events/EventArgs/ReceivingEffectEventArgs.cs
Exiled.Events/Extensions/Event.cs
Exiled.Events/Handlers/Player.cs
Exiled.Events/Handlers/Scp049.cs
Exiled.Events/Utils/NextEnumerator.cs
Exiled.Loader/Loader.cs
Exiled.Loader/PathExtensions.cs
Exiled.Permissions/Extensions/Permissions.cs

Documentation

---

Exiled.API/Features/Player.cs

Human lives matter too, CASSIE!

Make cassie actually say his announcements if they aren't SCPs.

---

Exiled.API/Features/Player.cs

Add Player.TryAddCandy(CandyKindID)

---

Exiled.CustomRoles/API/Features/CustomRole.cs

Remove `Role` from default Player Info
Add config to CustomInfo

Better CustomInfo for CustomRoles

---

Exiled.Events/Handlers/Player.cs

Enhancing documentation

---

Exiled.API/Features/Player.cs

Repair-Player.ArtificialHealth

---

Exiled.API/Features/Player.cs

Making easy to make Custom AHP

Player new Method AddAhp

---

Exiled.API/Features/Room.cs

rooms
(creds to @louis1706 for the tesla gate idea)

Add RoomIdentifier and TeslaGate to Room

---

Exiled.Events/EventArgs/LandingEventArgs.cs
Exiled.Events/Handlers/Player.cs
Exiled.Events/Patches/Events/Player/Landing.cs

Added a landing event with a brand new transpiler.

Landing Event

---

Exiled.Events/EventArgs/StartingRecallEventArgs.cs

I don't know how use Transpiler for finish this

Add new args in 049 starting recall

---

Exiled.API/Features/Player.cs

Forces the player to make noise, in order to be detectable by Scp939.

Added `Player::MakeNoise`

---

Exiled.API/Features/DamageHandler.cs
Exiled.API/Features/ExiledDamageHandler.cs
Exiled.API/Features/Player.cs

Re-works existing Player.Hurt methods and adds 2 new overloads, which eliminates the repeated code in them and makes it overall more useful for plugin devs.

Changes to Player.Hurt to make them more useful.

---

Exiled.Events/Patches/Events/Player/Handcuffing.cs
Exiled.Events/Patches/Events/Player/RemovingHandcuffs.cs

The following solves the problem.
- **Removing Handcuffs Event Args doesn't have player who uncuffed another player**

Handcuff dont work normally fixed

---

Exiled.API/Features/Items/Throwable.cs
Exiled.CustomItems/API/Features/CustomGrenade.cs
Exiled.Events/EventArgs/AnnouncingScpTerminationEventArgs.cs
Exiled.Events/Patches/Events/Cassie/SendingCassieMessage.cs
Exiled.Events/Patches/Events/Map/AnnouncingScpTermination.cs
Exiled.Events/Patches/Events/Map/PlacingBulletHole.cs
Exiled.Events/Patches/Events/Player/EscapingAndFailingEscapePocketDimension.cs
Exiled.Events/Patches/Events/Player/ThrowingItem.cs
Exiled.Events/Patches/Fixes/GrenadeFuseTimeFix.cs

The dev-branch version of #1040

Sl 11.2 dev

---

Exiled.API/Features/Player.cs

It's going to be needed on the Master

VeryImportant Repair bug on Hurt

---

Exiled.API/Features/Generator.cs

- just adding Room
Co-Authored-By: Nao <60253860+NaoUnderscore@users.noreply.github.com>

Add Room in Generator

---

Exiled.API/Enums/GrenadeType.cs
Exiled.API/Extensions/ItemExtensions.cs
Exiled.Events/EventArgs/ExplodingGrenadeEventArgs.cs
Exiled.Events/Patches/Events/Map/BreakingScp2176.cs

Add scp-2176 breaking event and include it in other random places

Integrate Scp-2176

---

Exiled.Events/EventArgs/InteractingScp330EventArgs.cs

The game was literally unplayable with this bug

Fixed SCP-330 safe candy count

---

Exiled.API/Extensions/ItemExtensions.cs
Exiled.API/Features/Attributes/ExiledSerializableAttribute.cs
Exiled.API/Features/Broadcast.cs
Exiled.API/Features/Camera.cs
Exiled.API/Features/DamageHandler.cs
Exiled.API/Features/Door.cs
Exiled.API/Features/Items/Ammo.cs
Exiled.API/Features/Items/Armor.cs
Exiled.API/Features/Items/ExplosiveGrenade.cs
Exiled.API/Features/Items/Firearm.cs
Exiled.API/Features/Items/FlashGrenade.cs
Exiled.API/Features/Items/Flashlight.cs
Exiled.API/Features/Items/Item.cs
Exiled.API/Features/Items/Keycard.cs
Exiled.API/Features/Items/MicroHid.cs
Exiled.API/Features/Items/Pickup.cs
Exiled.API/Features/Items/Radio.cs
Exiled.API/Features/Items/Scp244.cs
Exiled.API/Features/Items/Scp330.cs
Exiled.API/Features/Items/Throwable.cs
Exiled.API/Features/Items/Usable.cs
Exiled.API/Features/Player.cs
Exiled.API/Features/Toys/ShootingTargetToy.cs
Exiled.API/Structs/ArmorAmmoLimit.cs
Exiled.API/Structs/AttachmentIdentifier.cs
Exiled.API/Structs/Elevator.cs

Make certain docs make more sense and show up on the site. Also converts AmmoLimit to a const, because it makes more sense to be a const  
(also like my 6th live pr as of now lol)

Convert some inheritdocs into parameters

---

Exiled.API/Features/Player.cs

should repair the bug on the master too

Repair Error

---

Exiled.API/Features/Respawn.cs

somebody please stop me from making commits

Convert ticket properties from get to get and set

---

Exiled.Events/Handlers/Player.cs

This event is not just for medical items

UsingItem Description correct

---

Exiled.Events/Handlers/Player.cs

Docs fixes

---

Exiled.Events/Patches/Events/Player/DamagingShootingTarget.cs

Fix Toy object sinc mode 

---

Exiled.Example/Commands/ParentCommandExample.cs

I have seen that Exiled.Example did not have a ParentCommand template, so I have created one

Example ParentCommand

---

Exiled.Events/EventArgs/PlacingBloodEventArgs.cs
Exiled.Events/EventArgs/PlacingBulletHole.cs

Smol Changes <:

---

Exiled.CreditTags/CreditTags.cs

They are no longer rejected by the client

Fixed Exiled.CreditTags

---

Exiled.Events/EventArgs/ActivatingGeneratorEventArgs.cs

Updated docs due to the changes in the mechanism of the generators.

Update ActivatingGeneratorEventArgs docs

---

Exiled.Loader/Features/LoaderMessages.cs

The old sexiled chance was 14%, this makes it 6.9% or lower

Sexiled chance

---

Exiled.API/Features/Server.cs

Adding double ``Exiled.API.Features.Server::Tps`` property.

---

Exiled.API/Features/Room.cs
Exiled.Events/Handlers/Internal/MapGenerated.cs
Exiled.Events/Patches/Events/Player/Joined.cs

-Remove the useless CallDelayed
-Remove useless Error
-Repair the TeslaGate in Room

Repair ``TeslaGate`` in ``Room``

---

Exiled.API/Features/Intercom.cs
Exiled.API/Features/Map.cs

Added ``Intercom`` class.
Added ``Intercom.SpeechRemainingTime``.
Moved all Intercom stuff from the ``Map`` class to the new ``Intercom`` class. **_(Breaking changes)_**

Intercom class

---

Exiled.API/Features/Roles/Scp0492Role.cs
Exiled.API/Features/Roles/Scp049Role.cs
Exiled.API/Features/Roles/Scp079Role.cs
Exiled.API/Features/Roles/Scp096Role.cs
Exiled.API/Features/Roles/Scp106Role.cs
Exiled.API/Features/Roles/Scp173Role.cs
Exiled.API/Features/Roles/Scp939Role.cs

Fix scripts being null

---

Exiled.Events/EventArgs/RespawningTeamEventArgs.cs

Fix RespawnTicket issue

---

Exiled.API/Features/Player.cs

Learning how github works and stuff so just doing this as my first pull request. May do more contributions in the future that are bigger then this. I did this because thought it'd just be interesting to have people teleport to ragdolls as if they're reborned or something idk.

Added Ragdoll type to RandomTeleport

---

Exiled.API/Features/Player.cs

We are not YandereDev to use `else-if`, bruh

Added a switch in RandomTeleport method

---

Exiled.API/Enums/DoorType.cs
Exiled.API/Enums/KeycardPermissions.cs
Exiled.API/Features/Door.cs
Exiled.API/Features/Room.cs
Exiled.API/Features/Warhead.cs
Exiled.Events/Handlers/Internal/MapGenerated.cs

Door type & room.get(vector3)

---

Exiled.API/Features/Player.cs

Small feature that isn't really needed at all.
I tested it in game with my own complied Exiled.API and command so it should work unless I am small brain.

Added Camera type to random teleport

---

Exiled.Events/Patches/Generic/PlayerHasHint.cs

Sometimes NRE is thrown on this patch, so it's the sollution to that.
It happens to me when the player leaves the server while i try to show a hint to him.

Fix NRE on PlayerHasHint patch

---

Exiled.CustomItems/API/Features/CustomItem.cs
Exiled.CustomItems/API/Features/CustomWeapon.cs
Exiled.CustomItems/Commands/Spawn.cs

idk, maybe need other parameter in this like `needSetPreviousPlayer`, but i dont want to make breaking changes

`Pickup::PreviousOwner` support in CustomItems

---

Exiled.API/Enums/ThrowRequest.cs

``Exiled::API::Enums::ThrowRequest::CancelThrow``

---

Exiled.API/Features/Intercom.cs

Added ``Intercom.RemainingCooldown`` for getting or setting the intercom's cooldown.
Added ``Intercom.Reset()`` to reset the intercom's cooldown to zero.
Added ``Intercom.Timeout()`` to timeout the intercom

more funny for intercom

---

Exiled.API/Features/Player.cs

Reverts Exiled-Team/EXILED#1242

Revert "DisplayName is better like this"

---

Exiled.CustomRoles/API/Features/CustomRole.cs

- not tested and not sure if it's the only things to do i have just see it and wanted to finish it

Finish TODO

---

Exiled.CustomRoles/API/Features/Extensions/ParserExtension.cs
Exiled.CustomRoles/API/Features/Parsers/AbstractClassNodeTypeResolver.cs
Exiled.Events/Commands/Config/Merge.cs
Exiled.Events/Commands/Config/Split.cs
Exiled.Installer/CommandSettings.cs
Exiled.Installer/Program.cs
Exiled.Loader/ConfigManager.cs
Exiled.Loader/Loader.cs
Exiled.Patcher/Patcher.cs

Removes all "var" (that I could find) which aren't commented (mainly transpiler docs).
They did all build successfully:
ˢᵒ ᶦᶠ ˢᵒᵐᵉᵗʰᶦⁿᵍ ᵇʳᵉᵃᵏˢ ᶦᵗ'ˢ ⁿᵒᵗ ᵐʸ ᶠᵃᵘˡᵗ

Remove all vars which aren't in comments.

---

Exiled.Events/EventArgs/ItemAddedEventArgs.cs
Exiled.Events/Events.cs
Exiled.Events/Handlers/Player.cs

After picking up the item:
After giving an item through RemoteAdmin:

Adds the ItemAdded event

---

Exiled.API/Features/Scp173.cs
Exiled.Events/Patches/Generic/Scp173BeingLooked.cs

Based on @zhaguanyang server testing, prefix did not cause unstoppable peanut. Therefore, this is a transpiler version (and prefix is commented out in case of need to revert to it).
The only thing I did not add is the hashset NW pool because I never really used it in the prefix and I don't really understand it quite well (other than some locking mechanism maybe?). I don't think it served a purpose but it was there anyway so I remove it in transpiler, so that's really the only differences.

Bug fix scp173 looked at

---

Exiled.Events/Config.cs
Exiled.Events/Patches/Events/Map/ExplodingFlashGrenade.cs

Long story short, they would prefer the game to have this odd behavior. Therefore, I made configurable.

Got feedback from owner's that they rather have this be toggable.

---

Exiled.API/Features/Player.cs
Exiled.Events/Patches/Fixes/AntiCheatSpeedFix.cs
Exiled.Events/Patches/Fixes/MuteHandlerClear.cs

I rewrite `AntiCheatSpeedFix` and `MuteHandlerClear` patches, everything worked on my tests
(removed null check in `MuteHandlerClear`, i don't think it's necessary)

Some Patches

---

Exiled.API/Extensions/MirrorExtensions.cs
Exiled.API/Features/Cassie.cs

- i thinks it's would be better like this but not sure

little change on MessageTranslated

---

Exiled.Example/Events/PlayerHandler.cs

Guys we did it!!!!!!!! no more bugs in exiled!!!!!!!

`Exiled.Example` fix

---

Exiled.API/Features/Scp914.cs
Exiled.API/Features/Warhead.cs
Exiled.Events/Handlers/Internal/MapGenerated.cs

- Thanks ArseeniK to report it

Fix component not being reset

---

Exiled.API/Features/Door.cs

- Doc fixes
- `Door::Lock(DoorLockType)` has been [deprecated](https://discord.com/channels/656673194693885975/668651891944587264/1001531371342266398)
- arguments renaming

Door fixes

---

Exiled.Events/Patches/Events/Player/InteractingGeneratorEvents.cs

Yep, I already tested and everything seems to be working.
Waiting for a feedback 
~~It was difficult to test when the dev branch does not support the new update~~

`InteractingGeneratorEvents` to transpiler

---

Localization/README-ES.md
README.md

Added Spanish localization to EXILED README

Added Spanish Localization

---

Exiled.Events/EventArgs/TogglingOverwatchEventArgs.cs
Exiled.Events/Handlers/Player.cs
Exiled.Events/Patches/Events/Player/TogglingOverwatch.cs

`OnTogglingOverwatch`

---

Exiled.Events/Patches/Fixes/RoleChangedPatch.cs

Reverts Exiled-Team/EXILED#1388

Revert "RoleChanged to transpilers"

---

Exiled.Events/Patches/Events/Scp173/PlacingTantrum.cs

#1438 again 'cause idk what i did

Fixed PlacingTantrumEventArgs isAllowed and Cooldown

---

Exiled.API/Extensions/RoleExtensions.cs

This PR fixes `[...]FirstPersonMovementModule::FixedUpdate()` NREs.

Fix for various NREs

---

Exiled.API/Enums/AmmoType.cs
Exiled.API/Enums/DoorBeepType.cs
Exiled.API/Enums/EffectCategory.cs
Exiled.API/Enums/FirearmType.cs
Exiled.API/Enums/PluginPriority.cs

add seealsos to enums

---

Exiled.API/Features/Roles/Role.cs
Exiled.API/Features/Roles/Scp106Role.cs
Exiled.API/Features/Warhead.cs
Exiled.CustomItems/API/Features/CustomItem.cs

- Warhead fix
- Scp106Role::UsePortal fix

No breaking changes for `Role::Set` + Fixes

---

Exiled.API/Features/Roles/Scp096Role.cs
Exiled.API/Features/Room.cs

honestly this should take like 3 seconds to look at and be like "yup that's amazing good job thunder"

Scp096Role.Calm(), Room.RoomName

---

Exiled.Events/EventArgs/Scp939/ChangingFocusEventArgs.cs
Exiled.Events/EventArgs/Scp939/LungingEventArgs.cs
Exiled.Events/EventArgs/Scp939/PlacingAmnesticCloudEventArgs.cs
Exiled.Events/EventArgs/Scp939/PlayingSoundEventArgs.cs
Exiled.Events/EventArgs/Scp939/PlayingVoiceEventArgs.cs
Exiled.Events/EventArgs/Scp939/SavingVoiceEventArgs.cs
Exiled.Events/Handlers/Scp939.cs
Exiled.Events/Patches/Events/Scp939/Focus.cs
Exiled.Events/Patches/Events/Scp939/Lunge.cs
Exiled.Events/Patches/Events/Scp939/PlacingAmnesticCloud.cs
Exiled.Events/Patches/Events/Scp939/PlayingSound.cs
Exiled.Events/Patches/Events/Scp939/PlayingVoice.cs
Exiled.Events/Patches/Events/Scp939/SavingVoice.cs

Moved from https://github.com/Exiled-Team/Exiled-EA/pull/206

SCP-939 events

---

Exiled.Events/Patches/Generic/Scp173BeingLooked.cs

this patch didnt exist
im not really sure how to format this, also this could be changed because hard-to-read giant if statement

Fix Scp173Role.TurnedPlayers

---

Exiled.Events/EventArgs/Player/ChangingSpectatedPlayerEventArgs.cs
Exiled.Events/Patches/Events/Player/ChangingSpectatedPlayerPatch.cs

- actually having IL error code on line newobj
but everything else work
- Remove Setter and IDeniableEvent because client will not sync

Fix changing spectated player

---

Exiled.API/Features/Map.cs
Exiled.API/Features/Warhead.cs

* Warhead.AutoDetonate
* Warhead.OpenDoors
* Warhead.CloseBlastDoors()
* Warhead.TriggerDoors()
* Warhead.CanBeDetonated()

Add additional warhead API

---

Exiled.Events/EventArgs/Player/ChangingRoleEventArgs.cs
Exiled.Events/Patches/Events/Player/ChangingRole.cs
Exiled.Events/Patches/Events/Player/Spawning.cs

- Fixed error in `NewRole` setter
- Fixed rare items errors

Some random fixes

---

EXILED.props
Exiled.API/Features/Lift.cs
Exiled.API/Features/Player.cs

Player.Lift + Lift API

---

Exiled.Events/Patches/Events/Scp079/ChangingCamera.cs
Exiled.Events/Patches/Events/Scp914/UpgradingPlayer.cs

914 fix for process player / camera fix (desync)

---

Exiled.Events/EventArgs/Cassie/SendingCassieMessageEventArgs.cs

Add IDeniableEvent to SendingCassieMessageEv

---

Exiled.API/Features/Pickups/FirearmPickup.cs

- Fixing issue when spawning Disruptor it's instant deleted because No AMMO also base game spawn firearm with this property to true

IsDistributed = true; for Pickup

---

Exiled.Events/EventArgs/Player/TogglingFlashlightEventArgs.cs
Exiled.Events/Patches/Events/Player/TogglingFlashlight.cs

This reverts commit 80318dc6065bd493c1dd0a9a4f30460b83f612bf.

Revert "Fix FlashLight Event (#1565)"

---

Exiled.Events/EventArgs/Player/TriggeringTeslaEventArgs.cs
Exiled.Events/Patches/Events/Player/TriggeringTesla.cs

Reverts Exiled-Team/EXILED#1573

Revert "Remake TriggeringTesla Event"

---

Exiled.Events/EventArgs/Scp173/BlinkingEventArgs.cs

Fix BlinkCooldown

---

Exiled.CustomRoles/API/Features/CustomRole.cs

CustomRoles SpawnChance Feature

---

Localization/README-Русский.md

Update on Exiled installation (Russian)

---

Exiled.CustomItems/API/Features/CustomWeapon.cs

At the moment we only change on the server side, but not on the client side.

CustomWeapon: Update ammo on the client side

---

Exiled.API/Features/Items/Firearm.cs

Fix firearm ctor

---

Exiled.API/Features/DamageHandlers/GenericDamageHandler.cs

More seems like adding a null check

Fix NRE with CassieAnnouncement

---

Exiled.Events/Patches/Fixes/GrenadePropertiesFix.cs

Fixes https://discord.com/channels/656673194693885975/1077737420671422596

Fixes grenade projectile scale not obeying the item/pickup's scale.

---

Exiled.CustomItems/API/EventArgs/OwnerDyingEventArgs.cs
Exiled.CustomItems/API/Extensions.cs
Exiled.CustomItems/API/Features/CustomItem.cs
Exiled.CustomItems/API/Features/CustomWeapon.cs
Exiled.CustomItems/Commands/Give.cs
Exiled.CustomItems/Commands/Info.cs
Exiled.CustomItems/Commands/Spawn.cs
Exiled.CustomItems/CustomItems.cs
Exiled.CustomItems/Events/PlayerHandler.cs
Exiled.CustomItems/Exiled.CustomItems.csproj
Exiled.CustomRoles/API/Features/ActiveAbility.cs
Exiled.CustomRoles/API/Features/CustomAbility.cs
Exiled.CustomRoles/API/Features/CustomRole.cs
Exiled.CustomRoles/API/Features/Extensions/ParserExtension.cs
Exiled.CustomRoles/API/Features/Interfaces/ITypeDiscriminator.cs
Exiled.CustomRoles/API/Features/Parsers/AbstractClassNodeTypeResolver.cs
Exiled.CustomRoles/API/Features/Parsers/AggregateExpectationTypeResolver.cs
Exiled.CustomRoles/API/Features/Parsers/ParsingEventBuffer.cs
Exiled.CustomRoles/Commands/Give.cs
Exiled.CustomRoles/Commands/Info.cs
Exiled.CustomRoles/Commands/UseAbility.cs
Exiled.CustomRoles/CustomRoles.cs
Exiled.CustomRoles/Exiled.CustomRoles.csproj

Added lookup tables for CustomRole and CustomItem Get(string), Get(uint), Get(Type) methods.
Added CustomItem.Get(Type)
Added bool to CustomRole class that can be set to make the role not allow custom items in the inventory config to show the received item hint.
Support nullable types.

Just some minor stuff.

---

Exiled.API/Features/Items/Jailbird.cs
Exiled.API/Features/Pickups/JailbirdPickup.cs
Exiled.CustomItems/API/Features/CustomWeapon.cs

More property for JailBird

---

Localization/README-BR.md
README.md

Finally fixing this thanks to my last pull request being merged. Also took the chance to make some changes.

Firething/EXILED to Exiled-Team/EXILED // (PT-BR) Brazilian Localization Hotfix

---

Exiled.CustomItems/API/Features/CustomGrenade.cs

Not tested for now, gonna test it later

Throw Method for CustomGrenades

---

Exiled.Updater/Updater.cs

[Exiled.Updater] Better error message

---

Exiled.CustomItems/API/Features/CustomArmor.cs
Exiled.CustomItems/API/Features/CustomItem.cs
Exiled.CustomItems/API/Features/CustomWeapon.cs

Display message fix

---

Exiled.Events/Patches/Events/Player/Shot.cs

Fixed Shot event for non buckshot guns

---

Exiled.Events/EventArgs/Player/ThrowingRequestEventArgs.cs
Exiled.Events/Patches/Events/Player/ThrowingRequest.cs

Remove IsAllowed to "fix" #1746

ThrowingRequest

---

Exiled.API/Features/Pickups/Pickup.cs

Fix creating jailbird pickup

---

Exiled.Events/Patches/Events/Player/ProcessDisarmMessage.cs

Fix remove cuff event

---

Exiled.API/Features/Round.cs

Added a property for do an action at round end. (shutdown, none, restart)

Added Round::NextRoundAction

---

Exiled.API/Extensions/ItemExtensions.cs
Exiled.API/Extensions/MirrorExtensions.cs
Exiled.API/Extensions/RoleExtensions.cs

* Added `ItemExtension::GetCategory(ItemType)`
* Removed `RoleExtension::GetTeam(RoleTypeId)` cuz NW has same method

Extensions update

---

EXILED.props
Exiled.API/Features/Player.cs

`Player::CustomInfo` fix

---

Exiled.Events/EventArgs/Player/VoiceChattingEventArgs.cs
Exiled.Events/Patches/Events/Player/VoiceChatting.cs
Exiled.Events/Patches/Events/Scp079/ChangingSpeakerStatusAndVoiceChatting.cs

Removed old voice chat patch from ChangingSpeakerStatusAndVoiceChatting.cs and created VoiceChatting.cs for use instead of VoiceModuleBase VoiceTransceiver.ServerReceiveMessage for get the actual message.
And readded VoiceModule

Voicechatting

---

Exiled.Installer/Program.cs
Exiled.Installer/Properties/Resources.Designer.cs

Loader fix

---

Exiled.API/Extensions/MirrorExtensions.cs

Fix fake SyncVars

---

Exiled.Events/Events.cs
Exiled.Events/Patches/Fixes/KillPlayer.cs

My pr #1818 was mergedd but I forgot to remove test logs

Remove Test Logs Info miss in #1818

---

Exiled.Loader/Loader.cs

Fix reloading plugins

---

Exiled.API/Enums/DoorType.cs
Exiled.API/Features/Door.cs

- DoorType.Scp079Armory
- DoorType.Scp173NewGate

New DoorType

---

Exiled.Events/Patches/Events/Server/Reporting.cs

Fix Local and Cheater Report not firinng

---

Exiled.Events/EventArgs/Map/ChangedIntoGrenadeEventArgs.cs
Exiled.Events/Patches/Events/Map/ChangingIntoGrenade.cs
Exiled.Events/Patches/Generic/PickupControlPatch.cs

- Due that bug `item::Scale` property do nothing(Also that was related to #1898 , but anyway it was fixed)
- Plus, that pr includes some docs fixes

`Item::Scale` fix

---

Exiled.API/Features/Room.cs

Fix Room.ResetColor

---

Exiled.Events/Patches/Events/Player/PickingUpItem.cs

Fixed pickup locking when `ev::IsAllowed == false`

`PickingUpItem` event fix

---

Exiled.Events/Patches/Events/Player/FlippingCoin.cs

Tested
Fix for [IsTails from FlippingVoin is always false](https://discord.com/channels/656673194693885975/1124108078439202916)

Coin event fix

---

Exiled.API/Features/Npc.cs
Exiled.API/Features/Player.cs

Fixed NPC not being able to spawn + invisible and updated the player IsNPC documentation

Fixed NPC not being able to spawn + invisible

---

Exiled.API/Features/Player.cs

Fix Player.IsCuffed

---

Exiled.Events/EventArgs/Player/DamagingShootingTargetEventArgs.cs

Fix #1932 
Added a null check.

Fix damaging shooting target causing crash

---

Exiled.Events/EventArgs/Server/ChoosingStartTeamQueueEventArgs.cs
Exiled.Events/Patches/Events/Server/ChoosingStartTeamQueue.cs

- DevBranch is actually making everyone at ClassD when the game Start

Fix previous #1968 PR

---

Exiled.API/Extensions/MirrorExtensions.cs

Fix SendFakeTargetRpc and SyncVarDirtyBits Key

---

Exiled.API/Features/Items/Item.cs
Exiled.Events/EventArgs/Player/AimingDownSightEventArgs.cs
Exiled.Events/EventArgs/Player/ChangingMoveStateEventArgs.cs
Exiled.Events/EventArgs/Player/DryfiringWeaponEventArgs.cs
Exiled.Events/EventArgs/Player/ReloadingWeaponEventArgs.cs
Exiled.Events/EventArgs/Player/ShootingEventArgs.cs
Exiled.Events/EventArgs/Player/TogglingWeaponFlashlightEventArgs.cs
Exiled.Events/EventArgs/Player/UnloadingWeaponEventArgs.cs
Exiled.Events/Patches/Events/Player/ChangingMoveState.cs
Exiled.Events/Patches/Events/Player/FirearmRequestReceived.cs
Exiled.Events/Patches/Events/Player/Shooting.cs
Exiled.Events/Patches/Events/Scp106/Attacking.cs

e
- again fixed unity objects comparing in `Item::Get` (that was reason cringey crushes on my server)
- optimization and maybe fixes for Shooting and firearm-requests events (plus i changed ctors a lil bit, technically a breaking change)
- some todos
- removed some `ChangingMoveState` event functionality, cuz it will desync player
- fixed server crush in `Scp106::Attacking` patch

Some fixes or not

---

Exiled.API/Features/Player.cs

https://discord.com/channels/656673194693885975/1141509977396232273/1141509977396232273

UserIdsCache fix

---

Exiled.Events/Patches/Events/Player/Escaping.cs

This reverts commit f7108195168789cb440e7b7986d2dd7ce9ee3cde.

Update Escaping event for 13.2.0

---

Exiled.API/Extensions/MirrorExtensions.cs

Resync sync var fix

---

Exiled.API/Features/Doors/CheckpointDoor.cs
Exiled.API/Features/Doors/Door.cs
Exiled.API/Features/Room.cs
Exiled.Events/EventArgs/Player/KickingEventArgs.cs
Exiled.Events/Patches/Events/Scp939/PlayingSound.cs
Exiled.Events/Patches/Events/Server/RoundEnd.cs
Exiled.Events/Patches/Generic/DoorList.cs

- room light
- random transpiler
- everything related checkpoint door
- New RoundEnd patch, for a changed chaos condition(i tested it partially)

Many fixes

---

Localization/README-BR.md
Localization/README-CS.md
Localization/README-ES.md
Localization/README-PL.md
README.md

A lot of people from the Czech Republic use EXILED, why not add Czech Localization?
Courtesy of Yours Truly.

Add Czech Localization

---

Exiled.Events/Patches/Events/Player/TriggeringTesla.cs

Fix Tesla API

---

Exiled.API/Features/Round.cs

This reverts commit c3612c9d59a31be94cf6fba25a136e1155b91946.

Revert "Added ChaosTargetCount (#2106)"

---

Exiled.API/Features/Toys/Light.cs
Exiled.API/Features/Toys/Primitive.cs

https://github.com/Exiled-Team/EXILED/pull/2107#discussion_r1323705849

Remove BreakingChange

---

Exiled.Events/EventArgs/Map/SpawningTeamVehicleEventArgs.cs
Exiled.Events/Handlers/Map.cs
Exiled.Events/Patches/Events/Map/SpawningTeamVehicle.cs

e.g. when NTF choppa spawns or CI pickup truck spawn

New event: SpawningTeamVehicle

---

Exiled.API/Features/Room.cs

Someone didn't know how unity works.

---

Exiled.Events/EventArgs/Player/DyingEventArgs.cs

Deprecated the setter of DyingEventArgs::ItemsToDrop

---

Exiled.Events/EventArgs/Player/KickingEventArgs.cs
Exiled.Events/Patches/Events/Player/Kicking.cs
Exiled.Events/Patches/Generic/StaminaUsage.cs

StaminaUsage Patch now use Postfix instead of Transpiler & KickingEvent Transpiler

---

Exiled.API/Features/Round.cs

Yes it took more over a month to stop being lazy and PR this into dev :trollface:

ChaosTargetCounter

---

Exiled.API/Extensions/MirrorExtensions.cs

Fix Rpc and WriteExtensions dictionary

---

Exiled.API/Extensions/MirrorExtensions.cs

Fix Rpc and WriterExtensions dict

---

Exiled.Events/Patches/Events/Player/ChangingGroup.cs

Fix ChangingGroupEventArgs.NewGroup having no effect.

---

Exiled.Events/Config.cs

Changed following accepted suggestion https://discord.com/channels/656673194693885975/1170756050144727191/1171464836555735070. 
Yamato told me he was too lazy to do it :trollface:

Change default value of flashbang affect thrower

---

Exiled.Events/EventArgs/Server/EndingRoundEventArgs.cs
Exiled.Events/Patches/Events/Server/RoundEnd.cs

Should fix endround API and `ev.IsAllowed = false` not working

Ending round event fix

---

Exiled.Events/EventArgs/Player/ClosingGeneratorEventArgs.cs
Exiled.Events/EventArgs/Player/PickingUpItemEventArgs.cs
Exiled.Events/EventArgs/Scp244/OpeningScp244EventArgs.cs
Exiled.Events/EventArgs/Scp244/UsingScp244EventArgs.cs

who wrote this?

---

Exiled.Events/EventArgs/Map/SpawningTeamVehicleEventArgs.cs
Exiled.Events/Patches/Events/Map/SpawningTeamVehicle.cs

Convert Bool Prefix to Transpiler + fix. Related to this https://github.com/Exiled-Team/EXILED/issues/1842

SpawningTeamVehicle Transpiler + Add "team = ev.Team" which was not implemented 

---

Exiled.Events/Patches/Events/Player/Spawning.cs

No errors on startup, will test when new version will be released on clients

Spawning transpiler

---

Exiled.Events/Patches/Events/Player/Spawning.cs

Reverts Exiled-Team/EXILED#2241

Revert "Spawning transpiler"

---

Exiled.API/Features/Items/Item.cs

```ChangeOwner``` is a internal method.
Add ```ChangeItemOwner``` for a public one.

Add ```ChangeItemOwner```

---

Exiled.API/Features/Room.cs

Fixed Room.Blackout not turning off lights if duration was set to -1 (described in documentation as permanent duration)

Fixed Room.Blackout not turning off lights

---

Exiled.Events/Patches/Events/Scp2536/GrantingGift.cs

That fixes [report from discord](https://discord.com/channels/656673194693885975/1188212596730511440)

Emergency fix

---

Exiled.API/Enums/SpawnReason.cs

Added new SpawnReason for SCP-1507

SpawnReasons::Vocalize

---

Exiled.Events/EventArgs/Scp1507/SpawningFlamingosEventArgs.cs
Exiled.Events/Events.cs
Exiled.Events/Handlers/Scp1507.cs
Exiled.Events/Patches/Events/Scp1507/SpawningFlamingos.cs

Tested and working as intended

Flamingo respawn event

---

Exiled.API/Features/Generator.cs

how was this like this for 2 years

fix IsOpen setter for 079 generators

---

Localization/README-TR.md

better turkish

---

Exiled.Events/EventArgs/Scp049/FinishingRecallEventArgs.cs
Exiled.Events/Patches/Events/Scp049/FinishingRecall.cs

- i can't test this alone (Only test the way than there no IL Code error)

Fix scp049 respawning overwatch

---

Exiled.API/Features/Roles/FpcRole.cs

Original Pull Request: https://github.com/Exiled-Team/EXILED/pull/2242

Add `Fake Appearance`

---

Exiled.API/Features/Roles/FpcRole.cs

Reverts Exiled-Team/EXILED#2428

Revert "Add `Fake Appearance`"

---

Exiled.API/Enums/SpawnReason.cs
Exiled.API/Features/Roles/Role.cs

- SpawnReason.ForceClass => spawnReason.RemoteAdmin 
and Add SpawnReason.ForceClass

SpawnReason

---

Localization/README-DE.md
README.md

Added German localization to EXILED README

German localization

---

Exiled.Events/Patches/Events/Server/HumanSpawner.cs

`[Exiled::Events]` Fix `HumanSpawner` patch

---

Exiled.API/Features/Items/Firearm.cs

Breaking Changes:
- Create(FirearmType) -> Create(FirearmType, byte)
Fix:
- Fix ammo not being given to particle disruptor (and possibly other weapons)

[API] [Breaking Change & Fix] Firearm::Create & Constructor

---

Exiled.Events/EventArgs/Map/ElevatorArrivedEventArgs.cs
Exiled.Events/EventArgs/Map/ElevatorMovingEventArgs.cs
Exiled.Events/Handlers/Map.cs
Exiled.Events/Patches/Events/Map/ElevatorMovingAndArrived.cs

`[Exiled::Events]` Adding `Map::ElevatorMoving` and `Map::ElevatorArrived` events

---

Exiled.API/Extensions/RoleExtensions.cs
Exiled.API/Features/Player.cs

Add:
* Player::GrantLoadout()
* Player::GrantLoadout(RoleTypeId)
* RoleExtensions::GetStartingInventory(RoleTypeId)
Changes:
* Make GetStartingItems and GetStartingAmmo use GetStartingInventory
Breaking Changes:
* GetStartingInventory -> GetStartingItems

[Exiled.API] [Addition + Breaking Change] Player::GrantLoadout

---

Exiled.API/Features/Items/Firearm.cs
Exiled.API/Features/Items/Flashlight.cs
Exiled.API/Features/Items/Item.cs

Additions:
* Item::IsEmittingLight
Removals:
* Flashlight::Active

[Exiled.API] Item::IsEmittingLight

---

Exiled.Loader/Updater.cs

Since now [EXILED-DLL-Archiver](https://github.com/Exiled-Team/EXILED-DLL-Archiver) doesn't copy `Exiled.API.dll` and `SemanticVersioning.dll` to the Exiled dependencies folder as they are already loaded in northwood dependencies, so the file check for `Exiled.API` is no more needed as it's required to load `Exiled.Loader`

`[Exiled::Loader]` Fix loader can't find dependency

---

Exiled.API/Features/CustomStats/CustomHealthStat.cs
Exiled.API/Features/CustomStats/CustomHumeShieldStat.cs
Exiled.API/Features/CustomStats/CustomStaminaStat.cs
Exiled.API/Features/Player.cs
Exiled.Events/Patches/Fixes/FixStaminaBar.cs

* ``Player::MaxHumeShield``
* ``Player::HumeShieldRegenerationMultiplier``
* ``Player::MaxStamina``

[API] Features.CustomStats

---

Exiled.API/Extensions/CoroutineExtensions.cs
Exiled.API/Features/Player.cs

* ``CoroutineExtensions::Kill(CoroutineHandle)``
* ``CoroutineExtensions::IsRunning``
* ``CoroutineExtensions::ISRunningOrPaused``
* ``CoroutineExtensions::SetTag``
* ``Player::AddComponent<T>()``
* ``Player::RemoveComponent<T>()``
* ``Player::ResetInventory``

[API] Coroutine Extensions & Player additions

---

Exiled.Events/EventArgs/Scp079/AddingScanTargetEventArgs.cs
Exiled.Events/Handlers/Scp079.cs
Exiled.Events/Patches/Events/Scp079/AddingScanTarget.cs

`[Exiled::Events]` Add AddingScanTarget event (Handlers.Scp079)

---

Exiled.CreditTags/Commands/ShowCreditTag.cs
Exiled.Events/Commands/Config/Merge.cs
Exiled.Events/Commands/Config/Split.cs
Exiled.Events/Commands/PluginManager/Disable.cs
Exiled.Events/Commands/PluginManager/Enable.cs
Exiled.Events/Commands/PluginManager/Patches.cs
Exiled.Events/Commands/PluginManager/Show.cs
Exiled.Events/Commands/Reload/All.cs
Exiled.Events/Commands/Reload/Configs.cs
Exiled.Events/Commands/Reload/GamePlay.cs
Exiled.Events/Commands/Reload/Permissions.cs
Exiled.Events/Commands/Reload/Plugins.cs
Exiled.Events/Commands/Reload/RemoteAdmin.cs
Exiled.Events/Commands/Reload/Translations.cs
Exiled.Example/Commands/ParentCommandExample.cs
Exiled.Example/Commands/Test.cs
Exiled.Permissions/Commands/Permissions/Add.cs
Exiled.Permissions/Commands/Permissions/Group/Add.cs
Exiled.Permissions/Commands/Permissions/Group/Remove.cs
Exiled.Permissions/Commands/Permissions/Reload.cs
Exiled.Permissions/Commands/Permissions/Remove.cs

Actually the build can't success cause CommandSystem.Core.dll hasn't been updated yet

Missing member for all commands (changes in CommandSystem.Core)

---

Exiled.API/Extensions/ItemExtensions.cs
Exiled.API/Extensions/RoleExtensions.cs
Exiled.API/Features/Toys/Primitive.cs
Exiled.API/Structs/PrimitiveSettings.cs
Exiled.Events/Commands/PluginManager/Disable.cs
Exiled.Events/Commands/PluginManager/Enable.cs
Exiled.Events/Commands/PluginManager/Patches.cs
Exiled.Events/Commands/PluginManager/Show.cs
Exiled.Events/Commands/Reload/Configs.cs
Exiled.Events/Commands/Reload/GamePlay.cs
Exiled.Events/Commands/Reload/Permissions.cs
Exiled.Events/Commands/Reload/Plugins.cs
Exiled.Events/Commands/Reload/RemoteAdmin.cs
Exiled.Events/Commands/Reload/Translations.cs

* Improve ``ItemExtensions::IsThrowable(ItemType)``
* Improve ``ItemExtensions::GetMaxAmmo(FirearmType)``
* Improve ``RoleExtensions::GetTeam(RoleTypeId)``
* Made all ``PrimitiveSettings`` properties setters
* Modify Exiled.Events commands to use ``IPermissioned``
* Most PrimitiveSettings construtors removed
* PrimitiveSettings::Rotation made into Quaternation instead of Vector3
* Primitive::Create  methods mostly removed

[API] Primitive and extension improvements

---

Exiled.API/Extensions/EffectTypeExtension.cs

- Add `EffectTypeExtension::GetEffect(this EffectType)`
- Add `EffectTypeExtension::TryGetEffectBase(this EffectType, out StatusEffectBase)`
- Add `EffectTypeExtension::TryGetEffectBase<T>(out T)` where **T** is StatusEffectBase

`[Exiled::API]` Some additions to `Extensions/EffectTypeExtension.cs`

---

Exiled.Events/Patches/Events/Map/ExplodingFlashGrenade.cs

This fixed the issue for someone.

[Events] Fix flashbang

---

.github/workflows/dev.yml
docs/docs/Resources/Intro.md
packaging.ps1

Optimize CI 

---

Exiled.Events/Patches/Fixes/SlownessFix.cs

Slowness Effect Fix

---

Exiled.Events/Patches/Events/Map/DoorDamage.cs

Fixed patch error, and renamed for clarity.

BreakableDoor.ServerDamage fix

---

EXILED.props
Exiled.API/Enums/DangerType.cs
Exiled.API/Enums/DecontaminationPhase.cs
Exiled.API/Extensions/DangerTypeExtensions.cs
Exiled.CustomModules/CustomModules.cs
Exiled.Loader/Loader.cs

Reverts Exiled-Team/EXILED#2635

Revert "[EXILED9]"

---

Exiled.Example/EventHandler.cs

apparently debug was enabled when i compiled last time

[Exiled.Example] Fix Nameless skill issue 

---

Exiled.Events/Patches/Events/Player/TogglingNoClip.cs

this:
https://github.com/Exiled-Team/EXILED/assets/73160076/89d833d1-5b88-4a8c-9490-52d10e36d26f

[Events - TogglingNoClip] Fix IsAllowed value don't work properly

---

Exiled.API/Extensions/EffectTypeExtension.cs
Exiled.API/Features/Doors/Door.cs
Exiled.API/Features/Map.cs
Exiled.API/Features/Pickups/AmmoPickup.cs
Exiled.API/Features/Pickups/BodyArmorPickup.cs
Exiled.API/Features/Pickups/FirearmPickup.cs
Exiled.API/Features/Pickups/JailbirdPickup.cs
Exiled.API/Features/Pickups/KeycardPickup.cs
Exiled.API/Features/Pickups/MicroHIDPickup.cs
Exiled.API/Features/Pickups/Pickup.cs
Exiled.API/Features/Pickups/Projectiles/EffectGrenadeProjectile.cs
Exiled.API/Features/Pickups/Projectiles/ExplosionGrenadeProjectile.cs
Exiled.API/Features/Pickups/Projectiles/FlashbangProjectile.cs
Exiled.API/Features/Pickups/Projectiles/Projectile.cs
Exiled.API/Features/Pickups/Projectiles/Scp018Projectile.cs
Exiled.API/Features/Pickups/Projectiles/Scp2176Projectile.cs
Exiled.API/Features/Pickups/Projectiles/TimeGrenadeProjectile.cs
Exiled.API/Features/Pickups/RadioPickup.cs
Exiled.API/Features/Pickups/Scp1576Pickup.cs
Exiled.API/Features/Pickups/Scp244Pickup.cs
Exiled.API/Features/Player.cs
Exiled.API/Features/Roles/FpcRole.cs
Exiled.API/Features/Room.cs
Exiled.API/Features/Toys/Primitive.cs
Exiled.Events/EventArgs/Server/PreAssigningHumanRolesEventArgs.cs
Exiled.Events/EventArgs/Server/PreAssigningScpRolesEventArgs.cs
Exiled.Events/Features/Event{T}.cs
Exiled.Example/EventHandler.cs

* Add ``FpcRole::ClientRelativePosition``
* Correct ``FpcRole::RelativePosition``
* Fix ``Pickup`` null reference & wrong GameObject
* Fix null with ``EffectTypeExtensions``
* Fix ``Room.Get(RoomLightController)`` always returning null
* Fix ``Player::ArtificialHealth``

[API] Fixes & ClientRelativePosition

---

Exiled.Example/Example.cs
Exiled.Example/Translation.cs

i dont feel like this needs an explanation...

added example translation

---

Exiled.Events/EventArgs/Player/ChangingMoveStateEventArgs.cs

https://github.com/Exiled-Team/EXILED/issues/2690

Changing move state fix

---

Exiled.API/Features/Lockers/Chamber.cs
Exiled.API/Features/Lockers/Locker.cs
Exiled.Events/EventArgs/Map/SpawningItemEventArgs.cs
Exiled.Events/Patches/Events/Map/SpawningItem.cs

- Locker API Argument Exception Fix
- Chamber API Argument Exception Fix
- SpawningItem NullReference spam fix
- Remove `SpawningItemEventArgs::TargetDoor` property (It was causing the NRE Spam Issue)
- Removed all door stuff from the SpawningItem Patch (It was causing the NRE Spam Issue)

[Resonance] Locker API Fixes & CreatePickup Patch Changes

---

README.md

- For this to work I think Nao needs to enable widgets in the discord server settings

`[README]` Updated discord online member count for exiled reboot

---

Exiled.API/Features/Toys/Light.cs
Exiled.API/Features/Toys/Primitive.cs
Exiled.API/Features/Toys/ShootingTargetToy.cs
Exiled.API/Structs/LightSettings.cs
Exiled.API/Structs/PrimitiveSettings.cs
Exiled.API/Structs/ShootingTargetSettings.cs

- Created `LightSettings` struct
- Created `ShootingTargetSettings` struct
- New method `Light.Create(LightSettings)`
- New method `ShootingTargetToy.Create(ShootingTargetSettings)`
- Delete `ShootingTargetToy.Scale`, because `AdminToy.Scale` works in the same way

[Resonance] Create new structure to spawn toys

---

Exiled.Events/Handlers/Internal/Round.cs

New reboot invite

---

Exiled.API/Features/Pickups/Pickup.cs

Add category to the pickup
P.S Not sure if EProperty is needed

`[EXILED::API]` Pickup::Category

---

Exiled.CustomModules/API/Commands/CustomEscapes/Attach.cs
Exiled.CustomModules/API/Commands/CustomEscapes/Detach.cs
Exiled.CustomModules/API/Commands/CustomEscapes/Info.cs
Exiled.CustomModules/API/Commands/CustomEscapes/List/List.cs
Exiled.CustomModules/API/Commands/CustomEscapes/List/Registered.cs
Exiled.CustomModules/API/Commands/CustomEscapes/Parent.cs
Exiled.CustomModules/API/Commands/CustomItem/Parent.cs
Exiled.CustomModules/API/Commands/CustomRoles/Parent.cs
Exiled.CustomModules/API/Commands/CustomTeams/Info.cs
Exiled.CustomModules/API/Commands/CustomTeams/List/List.cs
Exiled.CustomModules/API/Commands/CustomTeams/List/Registered.cs
Exiled.CustomModules/API/Commands/CustomTeams/Parent.cs
Exiled.CustomModules/API/Commands/CustomTeams/Spawn.cs
Exiled.CustomModules/API/Commands/Gamemodes/End.cs
Exiled.CustomModules/API/Commands/Gamemodes/Enqueue.cs
Exiled.CustomModules/API/Commands/Gamemodes/Info.cs
Exiled.CustomModules/API/Commands/Gamemodes/List/List.cs
Exiled.CustomModules/API/Commands/Gamemodes/List/Registered.cs
Exiled.CustomModules/API/Commands/Gamemodes/Parent.cs
Exiled.CustomModules/API/Commands/Gamemodes/Start.cs

[Trackables Fix] Custom Modules Commands

---

Exiled.Events/Patches/Events/Player/Shot.cs

https://discord.com/channels/1261714360854646905/1286671066621808732

OnShot event now supports shooting into the sky

---

Exiled.CustomModules/API/Commands/CustomTeams/Spawn.cs
Exiled.CustomModules/API/Commands/Gamemodes/Start.cs
Exiled.Example/TestEscape/CustomEscapeScenarioType.cs
Exiled.Example/TestEscape/CustomEscapeType.cs
Exiled.Example/TestEscape/TestEscape.cs
Exiled.Example/TestEscape/TestEscapeBehaviour.cs
Exiled.Example/TestEscape/TestEscapeConfig.cs
Exiled.Example/TestGamemode/CustomGamemodeType.cs
Exiled.Example/TestGamemode/TestGamemode.cs
Exiled.Example/TestGamemode/TestGamemodeConfig.cs
Exiled.Example/TestGamemode/TestGamemodeGameState.cs
Exiled.Example/TestGamemode/TestGamemodePlayerState.cs
Exiled.Example/TestRole/CustomRoleType.cs
Exiled.Example/TestRole/TestRole2.cs
Exiled.Example/TestRole/TestRole2Behaviour.cs
Exiled.Example/TestRole/TestRole2Config.cs
Exiled.Example/TestTeam/CustomTeamType.cs
Exiled.Example/TestTeam/TestTeam.cs
Exiled.Example/TestTeam/TestTeamConfig.cs

[Resonance] More Custom Modules Examples & Small Command Fixes

---

Exiled.Events/Patches/Fixes/VoiceChatTpsFix.cs

Added TpsFix For VoiceChats
