Exiled-Team/EXILED

- EXILED_Events/Patches/DoorInteractionEvent.cs
If you're holding any item that doesn't have the keycard, now the event will be triggered again and will show the denied message. Whoops.
> Tiny little fix for a specific door interaction

- EXILED_Events/EXILED_Events.csproj
- EXILED_Events/Events/EventArgs.cs
- EXILED_Events/Events/MapEvents.cs
- EXILED_Events/Events/ServerEvents.cs
- EXILED_Events/Patches/BanUserOverride.cs
- EXILED_Events/Patches/LockerEventOverride.cs
- EXILED_Main/Extensions/MapExtensions.cs
- EXILED_Main/Extensions/PlayerExtensions.cs
- `Map.Broadcast(string message, uint duration, bool monospace)`, sends a global broadcast.
- `Map.ClearBroadcasts()`, clears all broadcasts.
- `Player.ClearBroadcasts()`, .NET Extension Method. Clears the broadcasts of a player.
Will be triggered before a ban is issued.
Contains: 
- `UserId`, set/get the UserId that will be written to the file.
- `Duration`, set/get the duration of the ban (in minutes).
- `BannedPlayer`, set/get the ReferenceHub of the player that will be disconnected.
- `Allow`, set/get if the player should be banned or not (true by default).
- `Reason`, set/get the reason.
- `FullMessage`, the message that will be broadcasted to the player.
Will be triggered everytime a player interacts with a locker.
Contains:
- `Player`, ReferenceHub of the player.
- `Locker`, the …
> Added all remaining Broadcast methods, added PlayerBan event, added LockerInteract event

- EXILED_Events/Patches/PlayerHurtEvent.cs
SCP 207 can damage the player in lower than 1 float damage based on the player's speed.
Player will die nevertheless when the HP is lower than 1f. So added that check for the event to fire correctly for SCP 207.
> fix for death by 207 was not triggered.

- EXILED_Events/Events/EventArgs.cs
- EXILED_Main/Extensions/PlayerExtensions.cs
No need to obsolete the old members, but I would recommend it if you want an accurate `Time`.
- `Time`, gets the time when the bullet was shot (inaccurate if changed with `Info = new Info...`
- `Amount`, can set/get the amount with this simple property. Cool.
- `Tool`, int representation of the "tool" used if you need it for whatever reason.
- `DamageType`, which returns the `DamageTypes.DamageType` (gets computed only if used, doesn't get recomputed if it's not `DamageType.None`)
> Made PlayerHurtEvent more intuitive and easier to use, fixed PlayerBan, obsoleted the old Broadcast function

- EXILED_Events/EXILED_Events.csproj
- EXILED_Events/Events/EventArgs.cs
- EXILED_Events/Events/ServerEvents.cs
- EXILED_Events/Patches/BanUserOverride.cs
- EXILED_Events/Patches/ElevatorInteractionEvent.cs
- EXILED_Idler/EXILED_Idler.csproj
- Fixed ElevatorInteractionEvent harmony instance typo ( _instance -> __instance )
- Deleted unused UnityEngine.Networking reference.
- Fixed UnityEngine.CoreModule hintpath in EXILED_Idler.csproj
- Added ReferenceHub Issuer in PlayerBanEvent
> Several Fixes and Added "Issuer" Referencehub to PlayerBanEvent

- EXILED_Events/Patches/PlayerJoinEvent.cs
When MuteHandler reloads, it doesn't clear the Mutes HashSet when re-reading the mutes.txt meaning that people who are not in the file anymore will stay muted untill the whole server restarts.
Also changed that foreach loop to just checking the actual player who joins. Why even use a foreach loop?
This fix also allows hotswapping and editing the mutes.txt to work.
> MuteHandler fixes

- EXILED_Events/Patches/CheckRoundEndEvent.cs
prevents the following errors
```
NullReferenceException
at (wrapper managed-to-native) UnityEngine.Component.GetComponentFastPath(UnityEngine.Component,System.Type,intptr)
at UnityEngine.Component.GetComponent[T] () [0x00021] in <cebd4f081718416185e10e6a32ed95bf>:0 
at Mirror.NetworkBehaviour.get_netIdentity () [0x0000e] in <1b0c0d2fb7eb4146b69a2a3af1f33755>:0 
at Mirror.NetworkBehaviour.get_isServer () [0x00000] in <1b0c0d2fb7eb4146b69a2a3af1f33755>:0 
at Mirror.NetworkBehaviour.SendRPCInternal (System.Type invokeClass, System.String rpcName, Mirror.NetworkWriter writer, System.Int32 channelId) [0x0001d] in <1b0c0d2fb7eb4146b69a2a3af1f33755>:0 
at RoundSummary.RpcDimScreen () [0x00006] in <272e168a6a4543f19545eec349160d10>:0 
at EXILED.Patches.CheckRoundEndEvent+<Process>d__2.MoveNext …
```
> stop triggered RoundEnd at RoundStart and prevents error at RoundRestart

- EXILED_Events/Patches/PlayerSpawnEvent.cs
__CharacterClassManager.NetworkCurClass__
```cs
set
{
if (NetworkServer.localClientActive && !base.getSyncVarHookGuard(8UL))
{
base.setSyncVarHookGuard(8UL, true);
this.SetClassID(value);
base.setSyncVarHookGuard(8UL, false);
}
base.SetSyncVar<RoleType>(value, ref this.CurClass, 8UL);
}
```
fix to ->
```cs
set
{
base.SetSyncVar<RoleType>(value, ref this.CurClass, 8UL);
}
```
> fix PlayerSpawnEvent being fire twice

- EXILED_Events/EventHandlers.cs
- EXILED_Events/Plugin.cs
- EXILED_Main/EXILED_Main.csproj
Adds the "exiled_drop_inventory" setting that allows to disable throwing items out of the inventory when the class changes to spectator/player leaves the game.
> Ability to turn off the drop of inventory

- EXILED_Events/Components/AntiAimbot.cs
Fixes a single disconnect disabling the Anti-Aimbot for every single connected player in the match (only players that joined after them would have the coroutine), and adds some sweetness of MEC's magic.
> Tied coroutines to GameObjects instead of a globally shared tag.

- EXILED_Events/Events/EventArgs.cs
- EXILED_Events/Events/ServerEvents.cs
- EXILED_Events/Patches/PreAuthEvent.cs
Currently usage of preauth event is almost impossible - rejecting a connection requires using NetDataWriter and writing rejection reasons codes and most of the developers doesn't know how to use it and reading anything else than UserId was even harder.
I made UserID variable readonly, because changing it here will cause an authentication issue in the primary auth and it can potentially cause an unwanted plugins interference (plugin can receive different UserID in preauth and join events, because another plugin has changed it here).
> Made preauth event useful

- EXILED_Events/Events/EventArgs.cs
- EXILED_Events/Events/PlayerEvents.cs
- EXILED_Events/Patches/PlayerReloadEvent.cs
Now PlayerReloadEvent is called twice, on animation start and on reload finish, this PR allows plugin to know which is it
> Make PlayerReloadEvent usable

- EXILED_Events/Events/EventArgs.cs
- EXILED_Events/Events/PlayerEvents.cs
- EXILED_Events/Patches/DropItemEvent.cs
Title.
Also please change current `Item` to `Pickup` and `SyncItemInfo` to `Item` in `DropItemEvent` on 2.0, it's confusing now.
> Make ItemDroppedEvent more usable

- EXILED_Main/Extensions/Item.cs
- EXILED_Main/Extensions/Player.cs
An extension to ReferenceHub that will get the badge they have on. Instead of doing ReferenceHub.GetRank().BadgeText, they can just do ReferenceHub.GetBadgeName() to simplify it some more
> Add way to get players badge easier, Checks for players being NTF added

- EXILED_Events/EXILED_Events.csproj
- EXILED_Events/Extensions/EventExtensions.cs
- EXILED_Permissions/EXILED_Permissions.csproj
Content:
- More information about an exception caused by a plugin that passed through `InvokeSafely`, now it is possible to look at the source with a static method.
- Correct compilation on the x64 platform for all projects, I didn't include Exiled_Idler because it will be deleted soon.
> Detailed information about the exception

- Exiled.Events/Patches/Events/Server/RoundEnd.cs
Apparently this bug still exists so I removed it. Zombies will not cause the negative scp bug because they are not real scps.
> oops negative scps

- Exiled.Events/Extensions/Event.cs
Since none of the events are protected during null calls, just return a value instead of throwing an exception.
> Get rid of ArgumentNullException on null event calls

- Exiled.API/Features/Map.cs
- Exiled.API/Features/Room.cs
- Exiled.API/Features/Round.cs
- Exiled.Events/Events.cs
- Exiled.Events/Handlers/Round.cs
- Exiled.Events/Patches/Events/Server/RestartingRound.cs
- Using ReadOnly collections instead of Lists to take away the ability to modify them.
- Take away the ability to assign a position and a name to the room.
- Updating API objects whenever the original unity object was destroyed (unity objects are managed from outside the managed CRL C# code, so they aren't collected by the GC and immediately destroyed).
- Change lazy initialization of a room zone to immediate.
> Revise the Map & Room API

- Exiled.Events/Patches/Events/Player/ChangingRole.cs
Before that there was no check for IsAllowed.
> Fixed escapingEventArgs.IsAllowed

- Exiled.Events/Commands/Reload/Configs.cs
- Exiled.Events/Commands/Reload/GamePlay.cs
- Exiled.Events/Commands/Reload/RemoteAdmin.cs
- Exiled.Events/Handlers/Server.cs
Adds a few events that are ran when the `reload` command is ran, so that plugins can respond to them easier.
> Added reload events

- Exiled.Events/Patches/Events/Player/Hurting.cs
Instead of dyingEventArgs.IsAllowed it was ev.IsAllowed and from that IsAllowd didn't work.
> DyingEventArgs ev.IsAllowed

- Exiled.Events/Patches/Events/Player/EscapingAndFailingEscapePocketDimension.cs
Even if IsAllowed = false was set, the player exited the pocket anyway
> Fix ignore IsAllowed EscapingPocketDimensionEventArgs

- Exiled.Events/Handlers/Server.cs
- Exiled.Events/Patches/Events/Server/LocalReporting.cs
- `Target`  is no longer null in the `LocalReportingEventArgs`.
- `Reason` changes the final reason.
- Rejecting a report no longer triggers a successful message for clients.
- `LocalReporting` converted to IL patch.
> Fix the LocalReporting event & convert to IL

- Exiled.Events/Patches/Events/Player/Hurting.cs
OnDying is now triggered when ev.Amount is -1 (used with nuke damage, player.Kill/Hurt)
> Fixed OnDying event

- Exiled.Events/Patches/Events/Server/SendingRemoteAdminCommand.cs
Commands can bypass plugins' ra command handlers, if contains REQUEST_DATA PLAYER_LIST SILENT
> Fix RA vulnerability

- Exiled.API/Features/Badge.cs
- Exiled.API/Features/Player.cs
- Using the structure prevents the `Badge` from getting into the managed heap.
- Optimization of getting `Badge` without creating a dictionary and manual parsing.
> Optimize the player global badge API

- Exiled.Loader/Loader.cs
This makes the error message a bit more descriptive.
> Include assembly name in Exiled.Loader error

- Exiled.API/Exiled.API.csproj
- Exiled.Events/Exiled.Events.csproj
- NuGet.config
NuGet.config overrides `globalPackagesFolder`, some peoples have this override in their global NuGet.config (like me). Some projects use the same dependencies, and it becomes terrible to watch all traffic with `dotnet restore` /`nuget restore`, **__Also nuget by default uses the `packages` folder as the packages folder if there is no global folder.__**
> Fix link to NWlib & remove NuGet.config

- Exiled.Permissions/Exiled.Permissions.csproj
- Exiled.Permissions/Extensions/Permissions.cs
I've a little conversation about permissions: 
- If I can use `.*` (or just `*` as I saw the code???) and `rk.*` as global and specific permissions, why can't I use subgroup permissions like `rk.subpermissions.*`?
- We check for the presence of a rank that is set in the config, but not the current one, why?
This PR contains:
- Ability to use permission for subgroups of any depth (ie `rk.sub.sub.sub.sub.sub.*`)
- Checking the native rank if the current one isn't set (ie the player has no rank, but it's set in the config)
- Fix NRE when `Dictionary::TryGetValue` was called with a null key
__This PR hasn't been tested, please do tests before accepting it.__
> Update Permissions::CheckPermission(this Player, string)

- Exiled.API/Features/Plugin.cs
After that you don't have to fuck with the required version, which is used for name tracking :)
> Follow the defauld required version with API

- Exiled.Events/Patches/Events/Scp096/AddingTarget.cs
- Exiled.Events/Patches/Generic/Scp096TriggeredByTutorial.cs
Tests have shown that simply excluding the player from targets doesn't work, we need to prevent `PreWindup`.
> Fix the `CanTutorialTriggerScp096` config

- Exiled.Events/Patches/Events/Player/Joined.cs
We'll get a NRE every frame in the ghost mode patch because there's no player & update bit of `CharacterClassManager :: NetworkMuted`.
> fix a NRE in ghostmode if the server isn't in online mode & update ccm muted bit

- Exiled.API/Enums/DoorType.cs
- Exiled.API/Extensions/DoorTypeExtension.cs
- Exiled.API/Extensions/String.cs
- Exiled.API/Features/Map.cs
- Exiled.API/Features/Room.cs
Added string extension "RemoveBracketsOnEndOfName" to fix duplicate prefab GameObject names for use with RoomTypes and DoorTypes.
Created an Enum "DoorType" to define the unique Door classes
Created an Extension "Type()" for the Door class which gets the DoorType using GetInstanceId() as a key for a dictiionary populated with Map.Rooms.
Changed the Room.GetDoorType() method to use the new "RemoveBracketsOnEndOfName()" extension.
> DoorTypes -- 

- Exiled.API/Features/Player.cs
Setting the rotation causes the camera to shift, i.e. the player's camera is behaving unnaturally.
> don't set player rotation on telepor

- Exiled.API/Features/Scp173.cs
Replaced as in Scp096 in favor of performance.
Note: this is a breaking change, all plugins that used it need to be recompiled.
> replace Scp173::TurnedPlayers with HashSet

- Exiled.Permissions/permissions.yml
Updated the permission file, used the YAML indents (2 spaces) & replaced `*` with `testplugin.moderator`, because `*` isn't even valid.
> update the permission yaml file

- Exiled.API/Enums/RoomType.cs
- Exiled.API/Features/Map.cs
- Exiled.API/Features/Room.cs
Using SECTR_Sector ensures it will get all rooms (Including pocket dimension).
Added error for calling Map.Room before rooms are created.
Added pocket dimension enums and setter for Room.Type().
Fixed the surface transform, need to use "Outside" because that's the correct transform for the surface.
> Adding pocket dimension room + Fix outside/Map room getter

- Exiled.Events/Patches/Events/Player/InteractingElevator.cs
Added a ForceCuff check in the InteractingElevators patch.
Players can't interact with elevators if they're cuffed (forced or not) and PlayerInteract.CanDisarmedInteract = false
> Added a ForceCuff check in InteractingElevators

- Exiled.Events/EventArgs/CreatingPortalEventArgs.cs
In CreatingPortalEventArgs, the listed SCP for ev.Player is SCP-096 instead of SCP-106.
> Corrected the listed SCP in Portal event

- Exiled.Events/EventArgs/SpawnedItemEventArgs.cs
- Exiled.Events/EventArgs/SpawningItemEventArgs.cs
- Exiled.Events/Handlers/Map.cs
- Exiled.Events/Patches/Events/Map/SpawningItem.cs
* New event: `Map::SpawnedItem` - Fires directly after an item is spawned, event args contains the item's pickup.
> Adding Map::SpawnedItem

- Exiled.API/Features/Round.cs
`Round::ForceEnd()` - Quickhand for `RoundSummary.singleton::ForceEnd` (ends the round, shows the end summary and stuff)
> Round::ForceEnd

- Exiled.Events/Patches/Events/Map/SpawningItem.cs
Fixing a typo in SpawningItem handler that said the wrong method was being patched
> Fixing documentation for SpawningItem event

- Exiled.API/Features/Player.cs
PlayerEffectsController:EnableByString has a success return value that Player::EnableEffect's string overload did not include.
> Adding return value to Player::EnableEffect

- Exiled.Events/EventArgs/BannedEventArgs.cs
- Exiled.Events/EventArgs/KickedEventArgs.cs
- Exiled.Events/Patches/Events/Player/Banned.cs
* Giving BannedEventArgs a well-deserved issuer (I know it was already there in BanDetails as IssuerId, but I mean we pass the banned player and that's also there)
* Renaming Player to Target in Kicked/Banned event args to keep consistent with Kicking/Banning events (Was more skeptical abt this change but it makes all the events have matching parameters [plus they're still the target of the ban regardless])
> Modifying Kicked/Banned events

- Exiled.API/Enums/ElevatorType.cs
- Exiled.API/Extensions/LiftTypeExtension.cs
- Exiled.API/Features/Map.cs
- Exiled.Events/EventArgs/InteractingElevatorEventArgs.cs
Adding Lift.Type() extension to match Door.Type(). Previously, ElevatorType enum was only used in InteractingElevatorEventArgs. Now it can be used anywhere via the Lift.Type() method. I also marked InteractingElevatorEventArgs.Type as obsolete, as the DoorType isn't in the InteractingDoorEventArgs, it shouldn't be here either (now that Lift.Type() is available).
> Adding Lift.Type() extension

- Exiled.Events/EventArgs/ChangingCameraEventArgs.cs
- Exiled.Events/Handlers/Scp079.cs
- Exiled.Events/Patches/Events/Scp079/ChangingCamera.cs
Scp079::ChangingCamera event - Patches `CallCmdSwitchCamera`, invokes before SCP-079 switches to a different camera.
> Adding Scp079 ChangingCamera event

- Exiled.Events/EventArgs/ChangingCameraEventArgs.cs
- Exiled.Events/Patches/Events/Scp079/ChangingCamera.cs
Now that `Map::GetCameraById` is a thing, I've shortened the ChangingCamera patch to use this method
> Shortening ChangingCamera patch

- Exiled.API/Extensions/RagdollExtensions.cs
Adding four extension methods to the Ragdoll class.
* `Ragdoll::GetRoom` - Returns the Room the ragdoll is in
* `Ragdoll::Role` - Returns the roletype of the role (for some reason this isn't provided, even though the name of the role is lol)
* `Ragdoll::Owner` - Returns the owner player (or null)
* `Ragdoll::Killer` - Returns the killing player (or null)
> Ragdoll extensions

- Exiled.Events/Patches/Events/Player/InteractingDoor.cs
* Base game feature: Users with bypass mode can open locked doors, exiled was overriding this feature with our InteractingDoor patch
* If a plugin sets `IsAllowed` to `false`, they still will not be able to open the door regardless of bypass mode.
Issue #348.
> Allowing users with bypass mode to open locked door (base game feature).

- Exiled.Events/EventArgs/EnteringPocketDimensionEventArgs.cs
- Exiled.Events/Patches/Events/Player/EnteringPocketDimension.cs
It adds the player who put the other player in the pocket dimension to the event
> Add 106 to entering pocket dimension

- Exiled.API/Features/Map.cs
- Exiled.Events/EventArgs/ElevatorTeleportEventArgs.cs
- Exiled.Events/Handlers/Scp079.cs
- Exiled.Events/Patches/Events/Scp079/Interacting.cs
* `ElevatorTeleport` event: Invoked before Scp-079 switches floors using elevators. Event args take player, camera, ap amount, and isAllowed
* Adding `Map::GetCameraByType(CameraType)` - Returns a `Camera079` with the given CameraType
> More 079 crap

- Exiled.API/Features/Respawn.cs
* `Respawn::TimeUntilNext` (int) - Returns the amount of time until the next respawn wave will spawn.
* `Respawn::CurrentlySpawning` (bool) - Returns whether or not the current respawn phase is spawning team or playing animations.
> Adding Respawn APIs

- Exiled.API/Features/Map.cs
- Exiled.Events/EventArgs/Interacting2536EventArgs.cs
- Exiled.Events/EventArgs/Spawned2536EventArgs.cs
- Exiled.Events/EventArgs/Spawning2536EventArgs.cs
- Exiled.Events/Handlers/Map.cs
- Exiled.Events/Handlers/Player.cs
- Exiled.Events/Patches/Events/Map/Spawning2536.cs
- Exiled.Events/Patches/Events/Player/PickingUpItem.cs
* Three events, `Spawning2536`, `Spawned2536`, and `Interacting2536`
* Two overloads for `Map::ForceSpawn2536`, one of which has no parameters and one has a player and bool parameter
> XMas-2020 API

- Exiled.Events/EventArgs/ChangingSneakEventArgs.cs
- Exiled.Events/EventArgs/ChangingSprintEventArgs.cs
- Exiled.Events/Handlers/Player.cs
- Exiled.Events/Patches/Events/Player/ChangingSneak.cs
- Exiled.Events/Patches/Events/Player/ChangingSprint.cs
* `ChangingSprint` - Fires when a player starts or stops sprinting
* `ChangingSneak` - Ditto, but with crouching/sneaking
Events don't currently have IsAlloweds, as changing the parameter doesn't affect anything (however, when the client starts/stops sprinting and sneaking, the variable does change which is why I can patch it). I'm not sure if this is possible or not.
> Creating events for sneak and sprint

- Exiled.Events/Commands/Show/Plugins.cs
* Shows amount of enabled and disabled plugins at the top
* Disabled plugins will now show `- Disabled` underneath the name
Figured this might help with some people narrowing down why their plugin isn't working (as this command previously didn't explicitly show whether a plugin was enabled or not
> Adding IsEnabled support into show plugins command

- Exiled.API/Features/Map.cs
- `Map::SpawnRagdoll(Player victim, DamageTypes.DamageType deathCause, Vector3 position, Quaternion rotation = default, Vector3 velocity = default, bool allowRecall = true)`
Spawns a ragdoll for a player (useful if: 1. Ragdolls aren't really spawned after a round restart; 2. You want SCP-049 to be able to respawn them.)
- `Map::SpawnRagdoll( RoleType roleType, DamageTypes.DamageType deathCause, string victimNick, Vector3 position, Quaternion rotation = default, Vector3 velocity = default, bool allowRecall = false, int playerId = -1, string mirrorOwnerId = null, float damage = -1f, string killerName = "Killer", int killerId = -1)`
Spawns a ragdoll based on a series of parameters. Most of them aren't actually used, but some other plugins might use them, so I felt like it was a good idea to …
> Added new Map::SpawnRagdoll methods

- Exiled.API/Features/Player.cs
- Exiled.Events/EventArgs/DestoryingEventArgs.cs
- Exiled.Events/EventArgs/DestroyingEventArgs.cs
- Exiled.Events/EventArgs/LeftEventArgs.cs
- Exiled.Events/EventArgs/VerifiedEventArgs.cs
- Exiled.Events/Handlers/Player.cs
- Exiled.Events/Patches/Events/Player/Destroying.cs
- Exiled.Events/Patches/Events/Player/Joined.cs
- Exiled.Events/Patches/Events/Player/Verified.cs
Joined - called once the player's object has been instantiated
Verified - called once the player has been verified
Destroying - called before the player's object is destroyed
Left - called before the player has left the server
Joined event is called right before Verified event is called, after them ChangingGroup event is called.
This was made to fix the current situation where Left event isn't called and during a silent round restart a plugin doesn't know which player is still on the server.
> Proper call order for common events

- Exiled.API/Features/Player.cs
disp is a toggle for if the hidden attribute on groups should apply. That means that if group's cover attribute is true, then hidden won't apply. This fixes that.
> Make Group setter actually work

- Exiled.Example/Example.cs
In the Discord people regularly ridicule plugins that use a Lazy
instance. Let's save Amathor from making some review comments and remove
Lazy instances from the Example that people use as a template for their plugins.
> Remove Lazy instance from example plugin

- Exiled.Permissions/Extensions/Permissions.cs
This will let users know the exact reason of a NullReferenceException with the message `Unable to parse permission config: ...`.
> Add a null check for RA config

- Exiled.API/Features/Map.cs
Adds an overload to Map.Broadcast to accept an Exiled.API.Features.Broadcast to mirror the overload on Exiled.API.Features.Player
> Add Map.Broadcast overload

- Exiled.API/Extensions/Item.cs
- Exiled.API/Extensions/Role.cs
- Exiled.API/Features/Respawn.cs
Removes a few .Where().FirstOrDefault() in exchange for .FirstOrDefault() and removes an unnecessary case.
> Remove Redundant .Where()'s

- Exiled.API/Features/Map.cs
- Exiled.Events/Handlers/Internal/MapGenerated.cs
- Exiled.Events/Handlers/Internal/Round.cs
By moving the ClearCache() call to when the map is generated, we guaruntee that the cache will always be cleared as close as possible to when the new map is generated, and should prevent issues pointed out in #428
> Fix for #428

- Exiled.Events/EventArgs/PreAuthenticatingEventArgs.cs
- Exiled.Events/Events.cs
Currently ev.Reject() causes rejection with `Unspecified error occured on the server` message
> Fixed PreAuthenticatingEventArgs.Reject()

- Exiled.Events/Patches/Fixes/Scp096FailEnrageFix.cs
- Exiled.Events/Patches/Fixes/Scp096PreWindupFix.cs
When a target is being added, if ev.IsAllowed is set to false in Scp096.AddingTarget event, and there are no other targets, SCP-096 will still enter the 'pre-windup' enraging animation, even if their targets list is empty.
This patch prevents that behavior, returning the function if _targets HashSet is empty.
> Fix for SCP-096 being able to enter 'pre-windup' with no targets.

- Exiled.Loader/ConfigManager.cs
So I removed the call to `Regex::Replace` because it was too old and nobody has anything like that. Apparently it'd break plugins using those methods because they now return `SortedDictionary` type, but that's their issue, right?
> Sorting config keys alphabetically instead

- Exiled.Events/Patches/Events/Player/Shoot.cs
Currently the patch used to add the events Player.Shooting and Player.Shot is a very large Prefix patch that always returns false.
These types of patches can be troublesome when the base-game method is changed, but those changes fail to get reflected in the patch properly. 
This changes the patch type to a transpiler, so as to not interfere with the normal logic of the anticheat included in the base method, and to allow easier updating of the patch in the future should things change.
> Turn the giant CallCmdShoot prefix patch into a transpiler.

- Exiled.API/Extensions/MirrorExtensions.cs
- Exiled.CustomItems/API/Features/CustomItem.cs
- Exiled.CustomItems/Commands/List/InsideInventories.cs
- Exiled.CustomItems/CustomItems.cs
- Exiled.CustomItems/Events/PlayerHandler.cs
- Exiled.CustomItems/Events/ServerHandler.cs
Currently, there are no items implemented in the Exiled-Team CustomItems that is not obviously a custom item and not a hack of some kind. (With the possible exception of shotgun, but it creates impact decals for every round it shoots, so it should be easy enough to see it's shooting multiple bullets at a time not some kinda damage hack)
A recent PR into CustomItems features a gun that is essentially server-side aimbot. 
This has raised a concerning thought: How would Northwood be able to determine the difference between someone using this item to kill a room full of people quickly, vs someone using an aimbot hack?
This PR is the answer to that question.
1. Players with a CustomItem in their hand will have their nickname changed to include the item's name, but only visible to spectators, …
> Allows NW to be aware of custom items that may impact gameplay

- Exiled.API/Extensions/Role.cs
- Exiled.API/Features/Map.cs
- Exiled.CustomItems/API/Features/CustomItem.cs
I feel like RoleType.GetRandomSpawnPoint is misplaced with Extensions.Role existing and it took me a minute to find that it was actually in Features.Map. I believe it makes more sense to place it in Extensions.Role.
> Move RoleType.GetRandomSpawnPoint extension to Extensions.Role

- Exiled.CustomItems/API/Features/CustomItem.cs
- Exiled.CustomItems/API/Features/CustomWeapon.cs
- Exiled.CustomItems/Commands/Spawn.cs
I hate naming my PRs.
- Added out param for CustomItem.TrySpawn() method.
- CustomItem.Spawn() now returns the Pickup component.
With stuff like this the dev can modify different settings of that specific pickup, or even access the GameObject & other components, which is necessary for some implementations.
> CI.Spawn Pickup

- .gitignore
- Exiled.Loader/Loader.cs
The point of it is that we only log that a plugin is enabled and not loaded, but we log when a dependency is loaded. I recently released an update for my plugin, it required the newest version of Exiled and breaks when it's not, so when the guy said he updated the plugin, I couldn't check it by logs because it was throwing an exception while enabling, I'd spend less time understanding this issue if I saw the plugin version.
> Plugin load logs

- Exiled.Events/EventArgs/ChangedRoleEventArgs.cs
- Exiled.Events/Handlers/Player.cs
- Exiled.Events/Patches/Events/Player/ChangingRole.cs
There is an issue with ChangingRole that causes it to run many times, with IsAllowed and IsEscaped set to true if IsAllowed is set to false in Escaping event. The Escaping event is the only way to accurately view escapes, but it is not possible to do the same with role changes. This new event occurs after a role is changed, to allow responding to the event correctly.
> Add ChangedRole event

- Exiled.Events/Patches/Events/Player/Handcuffing.cs
This update will have the Handcuffing event still be called regardless of the team checks. If the target is on the same team as the cuffer, `ev.IsAllowed` will default to `false`, but if set to `true`, the player will still be handcuffed. Other than that it works the exact same.
> Allow Handcuffing event.IsAllowed to override team checks.

- Exiled.API/Extensions/String.cs
DoorExtensions.GetDoorType now returns correct DoorType
> Fix DoorExtensions.GetDoorType (String.GetBefore)

- Exiled.CustomItems/API/Extensions.cs
I've added `ResetInventory(this Player player, List<string> newItems` method, that supports giving both normal items and custom items to a player.
> Player.ResetInventory(List<string>) extension

- Exiled.API/Features/Player.cs
Fixed issue where after setting item and then getting it, it returned item that was previously in hand
> Fixed not setting correctly item in player's hand

- Exiled.Events/Patches/Fixes/CassieNotSayingUnitNamesFix.cs
- Exiled.Events/Patches/Fixes/NineTailedFoxNamingRuleFix.cs
Cassie ignored unit names that were changed by `Map.ChangeUnitColor` method.
Using Regex I've removed color formatting when Cassie gets the unit name.
> Fixed Cassie not saying unit names, when their colors were changed

- Exiled.Events/EventArgs/ChangingMicroHIDStateEventArgs.cs
- Exiled.Events/EventArgs/UsingMicroHIDEnergyEventArgs.cs
- Exiled.Events/Handlers/Player.cs
- Exiled.Events/Patches/Events/Player/ChangingMicroHIDState.cs
- Exiled.Events/Patches/Events/Player/UsingMicroHIDEnergy.cs
I've added 2 new events:
`ChangingMicroHIDState` - it is called when the MicroHID changes it's state, for example from idle to rolling
`UsingMicroHIDEnergy` - it is called when the MicroHID uses it's energy
> ChangingMicroHIDState and UsingMicroHIDEnergy events

- Exiled.Events/Patches/Generic/Scp173BeingLooked.cs
This is a null check, therefore we should brfalse_s, otherwise this check is backwards. We are currently skipping everything if the gameobject's Player.Get() isn't null, we should only skip it when it IS null.
> Just fixing a pietro smallbrain moment

- Exiled.CreditTags/Config.cs
- Exiled.CreditTags/CreditTags.cs
- Exiled.CreditTags/Enums/InfoSide.cs
This PR adds FirstAvailable as an InfoSide for CreditTags. It finds the first unused spot to put the credit tag and then puts it there. 
I did change the default config option to FirstAvailable, as I believe it provides the most flexibility without any config changes by the server owner.
> Add FirstAvailable as an InfoSide for CreditTags

- Exiled.API/Features/Player.cs
Because the method uses ReferenceHub.fpc.Networkforce**Stop**Inputs; setting `player.CanSendInputs` to `true` actually means forcing stopping inputs and vice versa.
Yes, the fix is literally adding two "!!".
> Fixed Player.CanSendInputs being inverted

- Exiled.Events/Patches/Events/Player/Banned.cs
More info on #547, but essentially the issuer is null if their nickname has unsafe characters.
> Make the Banned event work with unsafe issuer nicknames

- Exiled.API/Features/Components/CollisionHandler.cs
- Exiled.API/Features/Map.cs
- Exiled.CustomItems/API/Features/CustomGrenade.cs
For some reason, this still wasn't a thing. The same method exists in `Exiled.CustomItems` but it isn't accessible, because you can use it only from a `CustomGrenade` class.
I wanted to add `explodeOnCollision` but because `Exiled.CustomItems` is inaccessible from `Exiled.API` I can't use a collider component from it.
> Added Map.SpawnGrenade() method

- Exiled.API/Features/Map.cs
- Exiled.API/Features/Player.cs
- Exiled.Example/Events/PlayerHandler.cs
It's an optional parameter and it just clears player's broadcasts before sending the new one.
I'm just too lazy to ClearBroadcasts() and then send the new one.
> Added shouldClearPrevious to Broadcast methods

- Exiled.CustomItems/Commands/Give.cs
- Exiled.CustomItems/Commands/List/Registered.cs
**Couple of small QoL changes:**
- **"ci give" command's player identifier is now optional:**
Using the give command without providing an identifier will choose the sender as the player who will receive the CustomItem, we're all too lazy to write our own name over and over again. (If an identifier was specified but was invalid, it will still throw a syntax error response)
- **~~You can now use the give command on SCPs:~~**  Reverted
~~While SCPs can't normally open their inventory, if you fake-change a syncvar using Mirror so the client thinks they're a human class, they will be considered SCPs, but be able to use their inventory normally, as well as their items. (That and also currently in the beta SCPs are able to access their items through hotkeys, but that might change in the future …
> CustomItems Commands Improvements

- Exiled.CustomItems/API/Enums/SpawnLocation.cs
- Exiled.CustomItems/API/Features/CustomItem.cs
- Exiled.CustomItems/CustomItems.cs
This PR adds the ability for Custom Items to use a "InsideLocker" dynamic spawn location. This will pick a random locker on the map, and replace the item that would normally spawn inside the locker with the custom item.
> Allows Custom Items to be spawned inside lockers.

- Exiled.Events/Patches/Generic/IndividualFriendlyFire.cs
This is a pretty janky solution that makes all calls to `CheckFriendlyFire(RoleType, RoleType, bool)` instead go to `CheckFriendlyFire(ReferenceHub, ReferenceHub, bool)` which allows us to get a player object from it. Unfortunately this means with each game update we'd have to make sure any new calls to `CheckFriendlyFire(RoleType, RoleType, bool)` get added (if you have a better solution please let me know, I couldn't think of any).
I tested with `IsFriendlyFire` both `false` and `true` between chaos and mtf. It all seemed to work as expected.
> Fix IsFriendlyFireEnabled

- Exiled.Events/EventArgs/KickedEventArgs.cs
- Exiled.Events/Patches/Events/Player/Kicked.cs
Since there's a KickingEventArgs, the old patch was useless and placed in the wrong place.
If you make a Prefix, the code will run BEFORE the player has been kicked.
With this method the code is still running before the player gets kicked, but it uses the base-game code, that handles various things with null checks, and the event code too.
Another problem with KickedEventArgs was their properties, `Reason` was a getter and setter, but it should be a getter since you can modify the `Reason` from KickingEventArgs, and `IsAllowed` is actually useless if KickingEventArgs already implements it.
Therefore I made it so that all properties are now getters, and removed `IsAllowed` cause that wasn't a property made for this event.
> Fixed KickedEventArgs

- Exiled.Events/EventArgs/DroppingNullEventArgs.cs
- Exiled.Events/Handlers/Player.cs
- Exiled.Events/Patches/Events/Player/ItemDrop.cs
**Fixed NRE**: When a player tries to drop an empty inventory slot, or a null item, a NRE occours.
**DroppingNullEventArgs**: Instead of fixing NRE only, we thought about the opportunity NW gave us to make a useful event for plugins. Indeed, this event is thrown before the actual DroppingItemEventArgs. It doesn't require an `IsAllowed` parameter since it'll always return to avoid NRE.
> Added DroppingNullEventArgs + Fixed NRE

- Exiled.API/Extensions/ItemExtensions.cs
- Exiled.API/Features/Items/ExplosiveGrenade.cs
- Exiled.API/Features/Items/FlashGrenade.cs
- Exiled.API/Features/Items/Throwable.cs
- Exiled.Events/Patches/Fixes/GrenadeFuseTimeFix.cs
This adds FlashGrenade and ExplosiveGrenade.SpawnActive() methods to spawn active grenades on the map.
This also adds a transpiler to fix the fact that there's no base-game way to properly set _fuseTime.
> Grenade api fixes

- Exiled.Events/Patches/Events/Player/Banned.cs
This resolves the issue with the current postfix where the event is called twice if there is already a logged ban for the given user/userid.
> Change banned event to transpiler

- Exiled.Events/EventArgs/RespawningTeamEventArgs.cs
I had an interesting moment today when I needed to change something very much in `RespawningTeam.Transpiler` patch, keeping the event working for the other EXILED plugins.
I just copied this transpiler to myself and realized that there was no way to copy exactly because the property was unavailable:
https://github.com/Exiled-Team/EXILED/blob/85fea72ec874a606d7c3b10f36b900afc1e0aee1/Exiled.Events/Patches/Events/Server/RespawningTeam.cs#L80
> Make `RespawningTeamEventArgs.SpawnableTeam` public

- Exiled.Permissions/permissions.yml
Because helper doesn't normally exist and definitely shouldn't have every permission.
> Let's have normal default permissions

- Exiled.Events/Patches/Events/Player/ChangingRole.cs
Reverts Exiled-Team/EXILED#681
Due to base-game issues, the method patched calls itself, which causes the `lite` bool to be ignored. This in turn breaks the functionality of our API. Until a better solution is found, this base-game functionality of being able to force-class someone as the same class they already are, must be removed, to retain functionality of the API.
> Revert "Fixes being unable to forceclass someone to the same role they alread…"

- Exiled.Events/EventArgs/InteractingShootingTargetEventArgs.cs
- Exiled.Events/Handlers/Player.cs
- Exiled.Events/Patches/Events/Player/InteractingShootingTarget.cs
An event that is fired when a player presses one of the buttons on a shooting target while the target is in sync mode.
Honestly I don't know if this event is worth merging as it only works while the target is in sync mode, but some devs may find it useful. Especially if some extra events are added like `ChangingShootingTargetSyncMode` to force the sync mode to always be on, `DamagingShootingTarget`, or some other events, I just haven't gotten to them yet.
> Interacting shooting target event

- Exiled.API/Features/Player.cs
Fixes an issue with AHP not working as intended. This just changes it to use the base game's ArtificialHealthManager which seems to be where all AHP values actually come from now.
> ArtificialHealth fix

- Exiled.API/Features/Door.cs
Currently GetDoorType() returns UnknownDoor for all of the entrance, heavy, and light containment doors when it should return the correct enum for it. That is now fixed.
> Fix GetDoorType()

- Exiled.API/Features/Player.cs
Currently you will get this error when setting Player.CurrentItem to null or `new Item(ItemType.None)`:
```
[2021-09-14 16:54:00.049 -04:00] [STDOUT] NullReferenceException: Object reference not set to an instance of an object
[2021-09-14 16:54:00.049 -04:00] [STDOUT]   at Exiled.API.Features.Player.set_CurrentItem (Exiled.API.Features.Items.Item value) [0x0001a] in <9d56c16099cf4088878254ced68c312e>:0
```
This PR fixes that.
(last PR I forgot to reset my branch, so it had the wrong commit, whoops)
> Fix setting CurrentItem to null or a None item

- Exiled.API/Features/Player.cs
Basically now you can straight up do this:
```cs
public bool Execute(ArraySegment<string> arguments, ICommandSender sender, out string response)
{
Player player = Player.Get(sender);
}
```
> Added ICommandSender override

- Exiled.API/Features/Server.cs
Idk why fastrestart was passed as true here, it makes clients not expect to get disconnected, then they immediately do so they do not reconnect.
> Fix Server.Restart not reconnecting players.

- Exiled.API/Features/Player.cs
If the server calls PlayerStats.HurtPlayer on a SCP-049-2, the attackerId must be the PlayerID of a valid player on the server, otherwise the 049-2 player's client will hit a nullref in an RPC and disconnect from the server as a result.
> Workaround for base-game client issue.

- Exiled.Events/EventArgs/ChangingIntoGrenadeEventArgs.cs
- Exiled.Events/Patches/Events/Map/ChangingIntoGrenade.cs
This patch re-implements the Map.ChangingIntoGrenade event, which will fire when an explodable pickup (IE HE grenade or 018) is turned into an active grenade when hit with an explosion.
The patch has been tested to not cause patching errors, but I have not yet verified the event works as expected and that base-game behavior isn't borked.
> Re-implement ChangingIntoGrenade event

- Exiled.Events/EventArgs/JumpingEventArgs.cs
Setting `ev.IsAllowed = false` won't prevent player from jumping, but it also won't send information about jump to the server. (for the server it will look like the player didn't jump at all)
Current comment states otherwise, so I adjusted it to say a correct behaviour.
> Adjusted comment in JumpingEventArgs

- Exiled.Events/Patches/Events/Player/EnteringPocketDimension.cs
Right now this event is being called before any base-game check is completed so it works even if game decides that target player shouldn't be moved in pocket dimension (this can happen if SCP-106 has high ping). This PR just fixes this problem
> Fixed EnteringPocketDimension event being called even if game refused the movement of player

- Exiled.API/Features/Player.cs
Initially I wanted to make a separate Ammo class that could be used as a Dictionary, which would also contain some cool methods and all that... Obviously that would've been the fancy way of doing this, so me being very lazy I instead opted for a few cool methods.
Either way, added the following methods to the `Player` class:
- `Player.AddAmmo(AmmoType, ushort)` to easily add ammo to the player's inventory.
- `Player.SetAmmo(AmmoType, ushort)` to set a specific ammo type to the specified amount.
- `Player.DropAmmo(AmmoType, ushort, bool)` to drop a specific amount of ammo. (I honestly don't have a clue as to what `checkMinimals` does)
- `Player.GetAmmo(AmmoType, ushort)` to get how much ammo the player has of a specific ammo type, not entirely necessary given `Player.Ammo` exists, but for …
> Player Ammo methods

- Exiled.API/Features/Player.cs
The server freezes when the main game and the exiled item list do not match. Rarely will 2 items with the same serial number appear on the list. The reason is not yet clear
> Server Freeze Problem

- Exiled.Events/Patches/Events/Player/ChangingRole.cs
The softlocks occur during death and escape, and are exasperated by EXILED. This method is ran on death and escape and has a while loop in it that calls a method that potentially wont remove the value from the while loop, creating a while-true.
This pretty much just forces the item to be removed from the inventory if it wasn't, so the while loop can't go on forever.
> Potential softlock fix

- .github/workflows/docs.yml
A change i made in PR #749 `docs.yml` was mistakenly reverted in commit [73adac92b9d072a13d699d213c90036abbf767b3](https://github.com/Exiled-Team/EXILED/pull/872/commits/73adac92b9d072a13d699d213c90036abbf767b3), this PR fixes that so CI will not  error when trying to build docs(somehow it didn't make its way back to dev???? ¯\_(ツ)_/¯)
> Fix mistakenly reverted docs.yml

- Exiled.Events/EventArgs/ReportingCheaterEventArgs.cs
Changed `reporter` to `issuer` 
Changed `reported` to `target`
Also yes this is indeed a breaking change
> Rename variables in ReportingCheaterEventArgs

- Exiled.API/Features/Player.cs
- Exiled.Events/Patches/Events/Player/ChangingRole.cs
Having MaxHealth tie directly to the Role.maxHP field makes it affect all players of that role. 
playerStats.StatModules[0].MaxValue is unsettable, thus we have no way to change a specific player's max-health within base-game code.
To allow us to still have and use the MaxHealth value for plugins, we need to detach it from base-game values. Plugins can still get/change the value as normal, and EXILED will change the value back to default for their new role when they change roles.
> Make MaxHealth great again

- Exiled.Events/Patches/Events/Player/Hurting.cs
This will prevent the event from being called when the target is dead/has godmode.
> Use the unused index on Hurting transpiler

- Exiled.API/Features/Room.cs
If a player joins the server later, the currentroom value will return null. This value remains blank until the player respawns. It throws an exception when we use "player.CurrentRoom.Players".
> CurrentRoom.Players Null exception fixed

- Exiled.Events/Patches/Events/Server/RestartingRound.cs
Basically, rnr is completely broken for servers that use frr, and it kicks everyone when the server restarts. This fixes that by forcing the server to use full restarts when the server is restarting.
> Fix disconnects after rnr while using frr

- Exiled.CustomItems/API/Features/CustomItem.cs
Currently, this results in the custom item being created as a generic API.Features.Items.Item type, always no matter what.
It prevents things like
`if (ev.Item is Firearm firearm)` from working properly in event handlers, and also causes InvalidCastExceptions to occur in events where ev.Item is a specific sub-type, like MicroHid and UsableItem events.
This implementation will ensure that the ItemBase created by the server is properly converted into the correct Features.Items sub-type, to prevent such issues.
> Fix for InvalidCastException in custom items.

- Exiled.Events/Patches/Events/Player/ChangingRole.cs
On dev branch event is called before game checks if player is verified, if he is a localplayer or if round is restarting which may lead to event false triggering. Now event is called after base game checks.
> Move ChangingRole event call after base game checks

- Exiled.API/Enums/KeycardPermissions.cs
KeycardPermissions has this attribute in base game. It's needed for bitwise operations (to check if player has permission to open a door)
> Add Flags attribute to KeycardPermissions

- Exiled.Loader/Loader.cs
In `exiled_loader` there is `is_enabled` property that does nothing. I've made so when set to `false` no plugins will be enabled (only loaded without any changes to the server).
This may be useful for testing, when you want to check some behaviour in vanilla without a need to yeet the Assembly-CSharp.
> Added option to disable EXILED from loading

- Exiled.API/Features/Items/ExplosiveGrenade.cs
- Exiled.API/Features/Items/FlashGrenade.cs
- Exiled.API/Features/Items/Flashlight.cs
- Exiled.API/Features/Items/MicroHid.cs
- Exiled.API/Features/Items/Radio.cs
- Exiled.API/Features/Items/Scp330.cs
- Exiled.API/Features/Player.cs
* Remove unnecessary item types in item constructors (eg. `new MicroHid(ItemType.MicroHID)` -> `new MicroHid()`)
* MicroHID
* Radio
* Flashlight
* Scp330
* FlashGrenade
* Added new ExplosiveGrenade constructor to take a GrenadeType rather than an ItemType (makes more sense than ItemType logically, the documentation specifies that FlashGrenade class should be used for flash grenades)
* Reworded documentation slightly for all the new methods
> Better item constructors

- Exiled.CustomRoles/API/Features/CustomRole.cs
This is a breaking change, but protected properties can't be used in configs apparently.
> These need to be public to allow for config stuff.

- Exiled.Events/Patches/Events/Warhead/StartingByCommand.cs
- Exiled.Events/Patches/Events/Warhead/StartingByServer.cs
Fixes #1006 and allows the event to trigger properly from all RA commands.
> Warhead event fix

- Exiled.API/Features/Items/Ammo.cs
- Exiled.API/Features/Items/Armor.cs
- Exiled.API/Features/Items/ExplosiveGrenade.cs
- Exiled.API/Features/Items/Firearm.cs
- Exiled.API/Features/Items/FlashGrenade.cs
- Exiled.API/Features/Items/Flashlight.cs
- Exiled.API/Features/Items/Item.cs
- Exiled.API/Features/Items/Keycard.cs
- Exiled.API/Features/Items/MicroHid.cs
- Exiled.API/Features/Items/Radio.cs
- Exiled.API/Features/Items/Scp330.cs
- Exiled.API/Features/Items/Throwable.cs
- Exiled.API/Features/Items/Usable.cs
- Exiled.API/Features/Player.cs
- Exiled.CustomItems/API/Features/CustomGrenade.cs
- Exiled.Example/Events/PlayerHandler.cs
Item.Create() should now be used by all plugins, while constructors will be reserved for EXILED internally.
This allows a single line of code to handle creation of items of any subtype with the correct subclass attached (resolves issues where gun ammo breaks etc if you simple `new Item(ItemType.E11SR)` instead of `new Firearm(ItemType.E11SR)`, amongst others)
Obsolete marked ctors will be made internal only in the future, as to alleviate all plugins breaking instantly when 5.0 releases.
> Re-work item API.

- Exiled.API/Features/Door.cs
- Exiled.API/Features/Log.cs
- Exiled.API/Features/Player.cs
- Added `Unlock(float, DoorLockType)` & `Lock(float, DoorLockType)` to Door class.
These were made both because there's a base-game extension that supports this, and because it eases work when locking doors for a specific amount.
*A few notes, I'm thinking of renaming `Lock()` to `ChangeLock()` so it stays consistent with the previous method, and I'm still deciding whether the `Lock()` method is necessary at all.*
- Added `Log.DebugObject()` to make debugging easier.
This was added so you can easily debug objects inputted inside parameters.
Example: `Player.List.Where(p => Log.DebugObject(p.IsDead));`
- Added `Player.GetModule<T>()` for easy accessing, instead of having to use `Player.ReferenceHub.playerStats`.
> API Improvements

- Exiled.API/Features/ExiledSerializable.cs
- Exiled.CustomItems/API/Features/CustomItem.cs
- Exiled.CustomRoles/API/Features/CustomAbility.cs
- Exiled.CustomRoles/API/Features/CustomRole.cs
Basically, this attribute can be used to register CustomItem's, CustomRole's and CustomAbility's without having to make two methods to register/unregister them, and then call them OnEnabled on whatever is it.
The attribute can be used more than once, so that you can define more "types" of CustomItem/CustomRole.
Quick example:
```
[ExiledSerializable(ItemType.GunRevolver)]
[ExiledSerializable(ItemType.GunCrossvec)]
public class MyCustomWeapon : CustomWeapon
{
}
```
This gets translated to:
```
new MyCustomWeapon() { Type = ItemType.GunRevolver }.TryRegister();
new MyCustomWeapon() { Type = ItemType.GunCrossvec }.TryRegister();
```
But it's fully handled by EXILED.
All the `TryRegister` and `TryUnregister` methods are now internal, this prevents people from using them so that they use the …
> Added ExiledSerializable attribute for Exiled features

- Exiled.Events/Handlers/Internal/MapGenerated.cs
This is the minimum delay we need to use, because I tried by adding 0.1f periodically (starting from 0.15f), and 1f seems the best delay. Also, with less than 1f, it doesn't work.
> Fixed `Map::Lockers` not returning all the generated lockers.

- Exiled.API/Features/Log.cs
I made this because it will optimise code a little bit, while you don't really need to .ToString() every time.
> Add string parameters overload to Log methods

- Exiled.API/Features/Log.cs
**Log.Assert** is a useful method for **debugging** which throws an exception when the value isnt the expected, stopping the execution of the method.
```cs
// only works if the build of the plugin is a DEBUG build. Otherwise the method will be ignored.
Player ply = Player.Get(3);
Log.Assert(ply != null, "The player 3 is null. THAT SHOULDNT HAPPEN!!"); 
SomeMethod(ply);
```
If the value isn't the expected (Not Null) it will log an error and stop the execution, therefore `SomeMethod` wont be called.
> Introducing Log::Assert

- Exiled.Events/EventArgs/BanningEventArgs.cs
OnBanning event returns duration in seconds, but not in minutes.
> BanningEvent Docs fix

- Exiled.Events/Patches/Events/Player/ActivatingWarheadPanel.cs
Another option is to have it fire even if the player doesn't have a card in hand at all, but that would make the starting index weird, plus it doesn't seem practical. Then again, what do i know
> Make unlocking surface warhead event fire regardless of card

- Exiled.CustomRoles/API/Features/CustomRole.cs
PlayerInfoArea.Role now is being propertly returned to player after RoleRemoved
> The great fix

- Exiled.CustomItems/API/Features/CustomItem.cs
- Exiled.CustomRoles/API/Features/CustomAbility.cs
- Exiled.CustomRoles/API/Features/CustomRole.cs
- Exiled.Loader/Loader.cs
The current attribute system makes it impossible to use the classes in configs correctly. This resolves that.
> Allow attribute-registered CustomItems, CustomRoles and CustomAbilities to be used as config objects.

- Exiled.API/Features/Player.cs
- Fixed player position trying to force ground
- Removed `Rotations` property
- Changed `Rotation` value from `Vector3` to `Vector2`
- `Rotation` property setter will now sync with the client
> Fixed player rotation setter and more

- Exiled.Events/EventArgs/SpawnedEventArgs.cs
- Exiled.Events/Events.cs
- Exiled.Events/Handlers/Player.cs
This PR adds `Spawned` event, it is called **after** player has fully spawned.
The difference between this event `ChangingRole`, and `Spawning` event is, that it is called last, after the player has been safely spawned (after the player's position has been set correctly).
The reason for introducing this event is my attempt to fix the very known bug. The bug is being unable to reliable set player's position after his spawn. The easy fix was adding a delay, but it didn't always worked.
The reason behind the bug is most likely they way a player is spawned - in short, the game tries to sets player's position, waits 0.2 seconds and then checks if it's valid (for example, the player has floor under them). If not, it tries again and again until the 50th time when the game gives up and kills the …
> Added `Spawned` event for the player

- Exiled.Events/Patches/Events/Map/ExplodingFragGrenade.cs
Fix when candy or Disruptor make an explosion it's have always say it's Server.Host instead of the attacker
> OnExplodingGrenade Fix

- Exiled.API/Features/Player.cs
- Exiled.API/Features/Roles/SpectatorRole.cs
- Exiled.Events/Events.cs
- Fixed `Player::CurrentSpectatingPlayers` returning also the player himself
- Removed setter for `SpectatorRole::SpectatedPlayer` because it doesn't syncs with the client
> Spectator properties fix

- Exiled.API/Features/Door.cs
Add an overload that only takes duration and lock type allowing _actual lock all doors_.
Changed some docs due to they don't consistent with what they do
> Door.LockAll

- Exiled.API/Features/Server.cs
Call PlayerStatsSystem RefreshConfigs to reset FF multiplier.
> BugFix, Call PlayerStatsSystem when setting FriendlyFire.

- Exiled.API/Features/Server.cs
Just makes it easier to put session variables on the server if people forget `Server.Host` exists (definitely not me).
> Server.SessionVariables

- Exiled.Events/Patches/Generic/Scp173BeingLooked.cs
Fix for problem is to inject check before if(flag) to prevent the observingPlayers to be updated. Attempting to add then remove then add is not sufficient because this code is not particularly safe. It is easier to prevent the player from being added than trying to remove them with the system NW designed.
> Bug fix to Scp 173 being looked at for can_tutorial_block

- Exiled.Events/EventArgs/UsingBreakneckSpeedsEventArgs.cs
- Exiled.Events/Handlers/Scp173.cs
- Exiled.Events/Patches/Events/Scp173/UsingBreakneckSpeeds.cs
Adds an event to 173 for using breakneck speeds. 
Allows for bypassing the cooldown (i.e. it will fire with `ev.IsAllowed == false` if on cooldown, setting it to true will allow the ability to run regardless of this cooldown).
> UsingBreakneckSpeeds event

- Exiled.CustomItems/Patches/PlayerInventorySee.cs
Now, `pinv` command will be log only `ItemType`, and i make it to log CustomItem's names
> `Exiled::CustomItem` PInv command Support

- Exiled.API/Features/Roles/Scp939Role.cs
- Exiled.Events/Patches/Generic/GhostMode.cs
Basically forces 939 to be able to see players in the list. I would do this in a separate plugin, however, the existence of the `TransmitData` patch in exiled makes that almost impossible to do without breaking something, so I figured this would be the best approach.
> Scp939Role.VisiblePlayers

- Exiled.Events/Patches/Generic/IndividualFriendlyFire.cs
@steven4547466 Again, sorry - Anyway, this should resolve the Micro.Fire issue (as it calls HitboxIdentifier.CheckFriendlyFire) which was that its logic path was different than transpiler's.
1. Prefix originally (The design before I touched) did not handle if the FriendlyFireCheck returning false, in which it should of called base game FriendlyFire (Which would of returned true) (likely why https://discord.com/channels/656673194693885975/933781456172486686 existed)
2. Prefix modified did not handle the Server.FriendlyFire path correctly, nor did it handle the return false because the code was modified for a transpiler approach, rather than the prefix. In addition, the biggest problem being # 1 -> This meant that it would always take the IDestructible path because the original prefix code …
> Bug fix ff prefix

- Exiled.API/Features/Items/Armor.cs
- Exiled.API/Structs/ArmorAmmoLimit.cs
- Exiled.CustomItems/API/Features/CustomArmor.cs
- Exiled.CustomItems/API/Features/CustomGrenade.cs
- Exiled.CustomItems/API/Features/CustomItem.cs
- Exiled.CustomItems/API/Features/CustomWeapon.cs
Added:
1. `CustomArmor` class
2. Fix of `CustomItem::OnPickingUp` not shows message and `CustomWeapon` properties are not sets
3. New properties in `Exiled::API::Features::Items::Armor`
4. `ArmorAmmoLimit` cast to basegame type
Questions:
> `Exiled::CustomItems` new features

- Exiled.Events/Patches/Events/Player/FirearmRequestReceived.cs
basegame code:
```cs
if (!curInstance6.AmmoManagerModule.ServerTryUnload())
break;
conn.Send<RequestMessage>(new RequestMessage(msg.Serial, RequestType.Unload));
```
Exiled code was inserted after `ServerTryUnload()`, and `IsAllowed = false` only canceled animation, now Exiled code inserted before `ServerTryUnload()` method
> `Player::UnloadingWeapon` fix

- Exiled.Events/EventArgs/ChangingDurabilityEventArgs.cs
Fixes the Invalid Cast error displayed by ChangingDurabilityEventArgs
> Invalid Cast Fix

- Exiled.API/Features/Map.cs
Ragdoll in light containment kept giving surface because it would only check below itself. Should also check above if the below check fails.
> Checks if ragdoll is in room by also checking above ragdoll.

- Exiled.Events/Patches/Events/Scp049/StartingAndFinishingRecall.cs
This calls OnFinishingRecall even if the person being recalled isn't a spectator, and it just sets IsAllowed to false if this is the case.
> Call finishing recall earlier

- Exiled.API/Features/Round.cs
Old `IsStarted` have a wrong sense. That property indicated `InProgress` status, instead of `Started` status.
Maybe that change isn't necessary, but sense of `IsStarted` not compare with `InProgress`, imho.
> Fix Round.IsStarted sense, added Round.InProgress

- Exiled.API/Features/Plugin.cs
- Exiled.API/Interfaces/IPlugin.cs
- Exiled.Loader/Loader.cs
This adds a little option which allows plugins to ignore the required version check. This is useful for plugins which do not expect to break across major version changes (LogArchiver) or ones which can fix themselves automatically if they do (SCPStats).
> Add IgnoreRequiredVersionCheck

- Exiled.Events/Patches/Events/Player/UsingRadioBattery.cs
Radio is in inventory of the `Server.Host`, wastes energy, and triggering an event with a null player
(I just made it so that event is not called in this case)
> `Player::UsingRadioBattery` event fix

- Exiled.Events/Patches/Events/Map/BreakingScp2176.cs
- Exiled.Events/Patches/Events/Map/ExplodingFlashGrenade.cs
The problem was when Yamato added the constructor and the indexes changed, I thought it would be clearer to use a DeclaredConstructor with arguments in those patches
> Fixes `ExplosionGrenade.Explode` + better understandable ctos in  `Explode` patches

- Exiled.CustomItems/API/Features/CustomGrenade.cs
old cringe code was:
```cs
if (!ev.IsAllowed)
ev.IsAllowed = false;
```
new code with #1347 pr(current dev):
```cs
ev.IsAllowed = false;
```
so It's not the same, and when using the flash as a CustomGrenade it caused errors
> `CustomGrenade::OnThrowing` fix

- Exiled.Events/Patches/Events/Map/AnnouncingNtfEntrance.cs
Fixed ``NineTailedFoxNamingRule.PlayEntranceAnnouncement`` patch. Fixed problems with parsing if unit name has any ``<>`` tag.
> Unit names parsing fix

- Exiled.Events/EventArgs/Player/PreAuthenticatingEventArgs.cs
- Fixed code broken by #148 - there are other values possible for that switch. No action should be taken then.
- Fixed seconds check in `Delay`. The expression was always false, because `&&` was used instead of `||`.
> Fix for code broken by #148 and fixed a broken if

- Exiled.API/Features/Core/TickComponent.cs
Fixes an ArgumentNullException in the TickComponent constructor. This is caused by calling CanEverTick's setter prior to instantiating boundHandles as CanEverTick calls .ToArray() on boundHandles.
> Fix TickComponent instantiation

- Exiled.API/Extensions/MirrorExtensions.cs
`SendFakeTargetRpc` serialize all arguments, but there is no serializer for `StringBuilder`, so we just `.ToString()`
> `MirrorExtensions::MessageTranslated` method fix

- Exiled.Events/Patches/Events/Server/RoundStarted.cs
Event patches the cringe method(for role selection on round start), that can invokes randomly 1 - 3 times (NW logic)
> Fix duplicate `RoundStart` event

- Exiled.Events/EventArgs/AimingDownSightEventArgs.cs
- Exiled.Events/Patches/Events/Player/FirearmRequestReceived.cs
yea, now event works for both states, but i think in Exiled 6.0 we need change event name to something like `ChangingAimStatus`, and I don't see the point of two props `AdsIn` and `AdsOut` instead of one, for example `AdsStatus`
> `Player.OnAimingDownSight` event fix

- Exiled.API/Features/Badge.cs
- Exiled.Events/Patches/Events/Player/ChangingRole.cs
- Removed cringe code in `Badge::GetHexColor`
- Properly fix for spawning items while escaping(before my fix items spawns on escape position, not on player spawn position💀)
- removed `if (oldRole == newRole)` checks, base game now support respawning as same role
> Spawning fixes

- Exiled.API/Features/Pools/HashSetPool.cs
- Exiled.API/Features/Pools/ListPool.cs
- Exiled.API/Features/Pools/StringBuilderPool.cs
Convert pools to use basegame pools under the hood. Keep all of our API while using northwood pools so that there's only one pool internally.
> Convert pools to use basegame pools

- Exiled.API/Features/Pools/DictionaryPool.cs
I believe the returned dictionary may always be the same, resulting in some broken cases with players. If someone wants to fix I'd be more than happy to add that, I just don't know how to fix atm :)
> Temporarily disable dict pool

- Exiled.Events/Patches/Events/Scp049/SendingCall.cs
Someone found a issue with the Call event args (049) that can be spammed to give zombies infinite shield lmao
> Fix Spamming Ability

- Exiled.CustomItems/API/Features/CustomItem.cs
- Exiled.CustomRoles/API/Features/CustomRole.cs
**CustomItems**:
Fixing events not being registered for custom items.
Fix for https://discord.com/channels/656673194693885975/1088086256900120679.
**CustomRoles**:
Fixing player position not changed if custom role has own spawn point.
Changed Init and Destroy methods (support of lookup tables like in CustomItems).
Changed Get and TryGet methods from int to uint (Id is uint).
Tested
> CustomItems and CustomRoles fix

- Exiled.Installer/Exiled.Installer.csproj
- Exiled.Installer/Program.cs
- Exiled.Updater/Exiled.Updater.csproj
- Exiled.Updater/Updater.cs
- Make Exiled.Installer return Code 1 when an exception is encountered during updating.
- Make Exiled.Updater not restart the server if the Installer returns code 1.
- Update Exiled.Installer to a .net6 app (from .netcore3) to support libssl3 on newer distros (like ubuntu 24.x+)
> Just some tidying up.

- Exiled.API/Features/Paths.cs
- Exiled.Events/Commands/Config/Merge.cs
- Exiled.Events/Commands/Config/Split.cs
Now when you use `econfig` command it'll save new value into loader config in NWAPI.
Also updated Paths so now it has actual information about loader config destination.
For #1762
> Config command

- Exiled.API/Features/Map.cs
When `disable_decontamination` is true, you cant force decontamination. The fix replaces methods which ignore this.
Tested
> `Map.StartDecontamination` does not work with `disable_decontamination` true

- Exiled.Events/Patches/Events/Player/EnteringPocketDimension.cs
- Scp106 Attack now don't always capture the player into the Pocket
> Fix EnteringPocketDimensionEventArgs

- Exiled.Events/Patches/Events/Warhead/Starting.cs
Fixes `Player` property in event always being `Server::Host`
> `Warhead::Starting` event fix

- Exiled.API/Extensions/SpawnExtensions.cs
At the moment the position `SpawnLocationType.Inside049Armory` is outside the armory. Adding in `ReversedLocations` fixes this and the position is inside the armory.
> Fix position `SpawnLocationType.Inside049Armory`

- Exiled.API/Features/Player.cs
I can imagine myself wanting to use `Player.Teleport(object)`, but not, because my player does not spawn at the right offset.
Behold, a solution! New method: `Player.Teleport(object obj, Vector3 offset)`.
Problem has been solved.
> Add offset param to teleport

- Exiled.API/Enums/AuthenticationType.cs
- Exiled.API/Features/Cassie.cs
- Exiled.API/Features/Player.cs
* Obsolete AuthenticationType.Patreon for removal in next breaking change
* Obsolete Cassie.CalculateDuration(string, bool) in favor of Cassie.CalculateDuration(string, bool, float) for next breaking change
> Complete TODOs

- Exiled.Events/Patches/Events/Player/DroppingAmmo.cs
Corrected the behavior that ``ev.AmmoType`` is actually using ItemType.
> Fix Dropping ammo event

- Exiled.API/Features/Items/Item.cs
- Exiled.API/Features/Items/Scp018.cs
018 is no more Explosion grenade, so that pr fixes invalid cast ex
> Scp018 `Item::Create` fix

- Exiled.Events/Patches/Events/Player/Banning.cs
1. Should be fixed #1962 (Cuz exiled patched method that call's another banning method. Second ban method is called by FF detector)
2. Banning event now has a transpiler
3. Tested and no issues
> FIX BanEvent not being trigger when the ban is done by ServerHost

- Exiled.Loader/Features/Configs/TypeAssigningEventEmitter.cs
> Fixed a NullReferenceException when loading configs

- Exiled.CustomRoles/API/Features/CustomAbility.cs
- Exiled.CustomRoles/API/Features/CustomRole.cs
Allow Custom Roles to easily calculate the max ammo a player can carry of a specific type, and set their ammo to that, by setting the ammo property value to ushort.MaxValue.
ushort.MaxValue - 1 can still be used to give them basically the normal 65k possible max.
Also allows for getting CustomAbilities by their type, rather than name.
> Smart ammo limits

- Exiled.API/Features/Core/Generic/EnumClass.cs
- Exiled.API/Features/Core/Generic/Singleton.cs
- Exiled.API/Features/Core/Generic/StaticActor.cs
- Exiled.API/Features/Core/Generic/UnmanagedEnumClass.cs
- Exiled.API/Features/Core/StaticActor.cs
- Exiled.API/Features/Player.cs
Added `EnumClass`, can be used within existing enums.
Added `UnmanagedEnumClass`, can be used within existing unmanaged data types.
Added `Singleton<T>`, a managed singleton object.
Added `StaticActor` and `StaticActor<T>`, a singleton using ECS and entirely managed by Exiled.
Made `Player` a `TypeCastObject`<T>`.
> ECS Improvements

- Exiled.API/Features/Pickups/Pickup.cs
- Exiled.API/Features/Player.cs
Of course it is what it is, however unless we re-define the dictionary from which we get all effects, that's the only way to fix it.
> Add `SoundtrackMute` to exceptions

- Exiled.API/Features/Core/Generic/Singleton.cs
- Exiled.API/Features/Pickups/Pickup.cs
- Exiled.API/Features/Player.cs
- Exiled.CustomRoles/API/Features/ActiveAbility.cs
- Exiled.CustomRoles/API/Features/KeypressActivator.cs
- Exiled.CustomRoles/Config.cs
Removed redundant hint message that resulted in multiple hints being sent to the player when an ability is successfully activated.
The keypress activator message takes priority over the UseAbility() message, as it can include both the activator messages (no selected ability, etc) as well as the CanUseAbility() response, or the name & description of the ability that's been used, so it's just simpler to handle all of these in one place.
This is not a breaking change, as ActiveAbility.ShowMessage(Player) still exists, it just isn't called by the base class code anymore, thus it has been marked Obsolete.
> Ability use hint changes

- Exiled.Events/Patches/Fixes/HurtingFix.cs
There used to be a null check here, at some point. I know because I added it, and my local variable for the player is still in the patch.
Removing the null check causes Npc.Destroy() to throw exceptions on  `CustomNetworkManager.TypedSingleton.OnServerDisconnect(conn);`
This re-adds the check to allow for proper disposal of NPCs when you no longer have need of their services.
> Fixing someones tiny brain

- Exiled.API/Features/Badge.cs
- Exiled.API/Features/Npc.cs
- Exiled.API/Features/Player.cs
- Exiled.API/Features/Roles/Scp106Role.cs
- Exiled.CustomItems/Commands/List/Tracked.cs
- Exiled.Events/Commands/PluginManager/Disable.cs
- Exiled.Events/Commands/PluginManager/Enable.cs
- Exiled.Events/Commands/PluginManager/Show.cs
- Exiled.Events/Events.cs
- Exiled.Events/Handlers/Internal/Round.cs
- Exiled.Events/Patches/Events/Player/ChangingGroup.cs
- Exiled.Events/Patches/Events/Player/TogglingOverwatch.cs
- Exiled.Events/Patches/Events/Player/Verified.cs
- Exiled.Loader/AutoUpdateFiles.cs
- Exiled.Loader/AutoUpdateFiles.tt
- docs/docs/Resources/Intro.md
- need to be merged with this [2143](https://github.com/Exiled-Team/EXILED/pull/2143) [2120](https://github.com/Exiled-Team/EXILED/pull/2120)
> SCPSL-experimental Update

- Exiled.Events/EventArgs/Scp0492/ConsumingCorpseEventArgs.cs
- Exiled.Events/Patches/Events/Scp0492/Consuming.cs
Scp049 resurrect ability calls zombie event.
Idk how is can be, but seems like patching generic classes is weird.
tested and confirmed by me
> Fix `Scp0492.ConsumingCorpse` event was called with `Scp049`

- Exiled.API/Features/Respawn.cs
- Letting people using NegativeValue to modify token
> ModifyToken

- README.md
I had a smooth brain and had this target the Halloween branch.
Anyways this readme update is for the English language, removing unnecessary comas, adding missing comas, fixing capitalization where needed, adding and removing apostrophes where needed, spelling fixes, removing redundant statements, and touching up the readme to be more professional.
> English touch ups to the Readme

- Exiled.Events/Patches/Fixes/GrenadePropertiesFix.cs
- Exiled.Events/Patches/Generic/PickupControlPatch.cs
IsSpawned is get only now so there are errors when theses methods are patched
> Fix Patch errors

- Exiled.API/Features/Core/EObject.cs
- Exiled.API/Features/Core/Generic/EnumClass.cs
- Exiled.API/Features/Core/Generic/UnmanagedEnumClass.cs
- Exiled.API/Features/Core/StaticActor.cs
- Exiled.API/Features/Core/TickComponent.cs
- Exiled.API/Features/Core/TypeCastMono.cs
- Exiled.API/Features/Core/TypeCastObject.cs
Unnecessary caste removal
`this as T as TObject` to `this as TObject` because TObject is a superclass of T or T.
`is not EObject outer ? null : outer ` to  ` as EObject  `.
Fix usage of non init field
`ToString() => name`  to `ToString() => Name` because `name` is init after the first call of `Name`.
New method
```cs
public static StaticActor CreateNewInstance<T>()
where T : new() => CreateNewInstance(typeof(T));
```
To ensures that there is a (public) constructor to avoid cases where the type has no constructor. It is still possible to use Get even in the case of a privet constructor if we use T Get<T>(Type type). The advantage of this modification allows future optimization of the code if necessary
> Add doc, Fix bug, code simplification

- Exiled.API/Enums/SpawnReason.cs
They pointed out to me that nw doesn't use "Vocalize" but uses "Revived"
> Removed SpawnReason::Vocalize

- Exiled.Events/Features/Event.cs
- Exiled.Events/Features/EventExceptionLogger.cs
- Exiled.Events/Features/Event{T}.cs
the same as #2183 but for dev branch
> No breaking changes.
>
> I extracted error logging from Exiled.Events.Features.Event.InvokeSafely() into a separate public static class.
>
> This can be useful for patching, logging errors not only to the console but also to services like Sentry, Hawk, DataDog, or any other destination of choice.
> `[Exiled::Events]` (Addition) `EventExceptionLogger` to capture event exceptions.

- Exiled.API/Features/Core/Generic/EnumClass.cs
- Exiled.API/Features/Core/Generic/UniqueUnmanagedEnumClass.cs
- Exiled.API/Features/Core/Generic/UnmanagedEnumClass.cs
- Exiled.API/Interfaces/IEnumClass.cs
- Exiled.Events/Events.cs
One of a variants of fixes.
Getting a values from all enum classes to fill values collections so no more NRE.
> `[Exiled::API]` EnumClasses fix

- Exiled.API/Features/Core/Generic/UniqueUnmanagedEnumClass.cs
Yeah, main problem was that we casted uint to int.
Tested on UUE, that are presented in exiled.
> `[Exiled::API]` `UniqueUnmanagedEnumClass` fix

- Exiled.API/Features/Pickups/BodyArmorPickup.cs
There's an NRE cause `BodyArmor::MovementSpeedMultiplier` calls `BodyArmor::ProcessMultiplier()` which change the value according to the player's team, which is null when the item is initialized
> `[Exiled::API]` NRE when getting MovementSpeedMultiplier

- Exiled.API/Features/Room.cs
- Exiled.CreditTags/CreditTags.cs
- Exiled.Events/Patches/Events/Scp106/ExitStalking.cs
* Disabled CreditTags until it is back -> Causes crash
* Fix Room::AreLightsOff
* ExitStalking event preventing stalking entirely somehow
> [API, Events, CreditTags] Bug fixes

- Exiled.API/Extensions/CommonExtensions.cs
so uhhhhhh..... it's an int not a float. mb
Reverts Exiled-Team/EXILED#2616
> Revert "Fix GetRandomValue out of range"

- Exiled.API/Extensions/CommonExtensions.cs
IEnumerable values can change when reiterated, meaning that if we use a random prompt for the condition, the enumerable will change giving a different length in the time of making a random value.
Meaning that for example:
```
int[] t = [1,2,3]
t.GetRandomValue(x => Random.value < 0.1);
```
will throw an exception.
This PR basically avoids multiple enumeration by first converting the IEnumerable to an array.
> CommonExtensions.GetRandomValue

- Exiled.Events/Patches/Fixes/SlownessFix.cs
Misc.MagnitudeIgnoreY is already absed and FpcMotor._lastMaxSpeed needed that abs (to prevent cheating in backwards speed)
> `[Exiled::Events]` Slowness fix part 2

- Exiled.Loader/LoaderPlugin.cs
Most of the time NRE happens when config is not correct (no exceptions from plugin api lol)
> Fix NRE while loading

- Exiled.API/Features/CustomStats/CustomHumeShieldStat.cs
- Exiled.API/Features/DamageHandlers/CustomDamageHandler.cs
- Exiled.Example/EventHandler.cs
* Fix null in DamageHandlerBase::Base
* CustomHumeShieldStat not allowing 0 max shield (would go to default max)
> [API] Fix issues

- Exiled.CustomModules/API/Features/CustomItems/CustomItem.cs
Current name is a bad one, calling .ToHashSet() every time property is accessed is heavily unoptimized, as it basicaly calls HashSet.Add for every item
> CustomItemsUnhold & CustomItemsHolded

- Exiled.API/Features/Server.cs
Adds a method called `ServerWhitelisted` that lets the user get the Whitelist loaded by SL
> `[Exiled::API]` ServerWhitelisted

- Exiled.API/Features/Doors/Door.cs
- Exiled.API/Features/Items/Armor.cs
- Exiled.API/Features/Items/Firearm.cs
- Exiled.API/Features/Items/Item.cs
- Exiled.API/Features/Items/Usable.cs
- Exiled.API/Features/Pickups/Pickup.cs
- Exiled.API/Features/Player.cs
- Exiled.API/Features/Round.cs
- Fixed item pickup time
- Fixed `ParentCheckpointDoor` internal set
- Fixed `AntiSCP207` item creation
- Fixed `ev.Player.UseItem()` doesn't call an event
> [Resonance] Small fixes

- Exiled.API/Features/Toys/AdminToy.cs
- Exiled.API/Features/Toys/Light.cs
- Exiled.API/Features/Toys/ShootingTargetToy.cs
- Rework `Light.Create()` to more right way
- Rework `ShootingTargetToy.Create()` to more right way
> [Resonance] Update toys

- Exiled.API/Features/Generator.cs
- Exiled.API/Features/Items/Item.cs
- Exiled.API/Features/Items/Scp244.cs
- Exiled.API/Features/Items/Scp330.cs
- Exiled.API/Features/Items/Usable.cs
- Exiled.API/Features/Pickups/Pickup.cs
- Exiled.API/Features/Pickups/Projectiles/Projectile.cs
- Exiled.API/Features/Player.cs
- Exiled.API/Features/PrefabHelper.cs
- Exiled.API/Features/Ragdoll.cs
- Exiled.API/Features/Workstation.cs
- Make rotation optional for `Pickup.Spawn`, `Pickup.CreateAndSpawn`, `Projectile.Spawn`, `Projectile.CreateAndSpawn` and `Ragdoll.CreateAndSpawn`
- Fix zero `Quaternion`
> [Resonance] Quaternion fixes

- Exiled.API/Features/Lift.cs
- Exiled.API/Features/Room.cs
- Fix room was null, when trying to access it from `ElevatorDoor.Room`
> [Resonance] Fix null room in elevator door

- Exiled.API/Features/Core/EObject.cs
- Exiled.CustomModules/API/Features/CustomRoles/RoleBehaviour.cs
- Exiled.CustomModules/API/Features/ModuleBehaviour.cs
- Exiled.CustomModules/API/Features/Pawn.cs
- Exiled.Example/Example.cs
- Exiled.Example/Exiled.Example.csproj
- Exiled.Loader/Loader.cs
Fixed Pawn.cs being null if try to use it by Player::Get().Cast<Pawn>(). Adding a method for load a constructor without any param or constructor. Removing abstract from RoleBehaviour.cs for allow the creating of an instance. Added custom role example under Exiled.Example for testing purpose.
> [ONGOING-FIX] - Fixed Pawn class being null and command fix and constructor error. Need to be fixed GameObject being null.

- Exiled.API/Extensions/DamageTypeExtensions.cs
- Exiled.API/Features/DamageHandlers/DamageHandlerBase.cs
- Fix player being kicked by applying `FirearmDamageHandler` damage to him (MessageHandler: InvalidOperationException Unknown damage type.)
- Add missing `DeathTranslations`
> [Resonance] Fix DamageHandler

- Exiled.API/Extensions/EffectTypeExtension.cs
- Exiled.API/Features/Items/Firearm.cs
- Exiled.API/Features/Player.cs
- Fix `EffectCategory` setter (previously always return None)
- Fix firearms, don't enable flashlight when created
> [Resonance] Fix flags set

- Exiled.API/Features/Player.cs
- Exiled.API/Features/Server.cs
Let's you scale down or up everything that has a NetworkIdentity
> `[EXILED::API]` Adding ScaleNetworkIdentityObject

- Exiled.API/Features/Map.cs
Spawns rats.
(What to you expect something incredible nope it just spawns rats)
> `[EXILED::API]` Adding SpawnMice

- Exiled.Events/EventArgs/Player/PlayingAudioLogEventArgs.cs
- Exiled.Events/Handlers/Player.cs
- Exiled.Events/Patches/Events/Player/PlayingAudioLog.cs
This adds a way to stop the audio logs, currently only one that is sitting on the table of the old 939 room, This works and the deniable works too
> `[EXILED::EVENTS]` Adding PlayingAudioLog

- Exiled.Events/Patches/Fixes/NWFixDetonationTimer.cs
**Describe the changes** 
Fixes https://git.scpslgame.com/northwood-qa/scpsl-bug-reporting/-/issues/396
**What is the current behavior?** (You can also link to an open issue here)
Games just takes the first Scenario, 120 seconds and just uses that if the value is not the same as one of the scenarios
**What is the new behavior?** (if this is a feature change)
Takes the nearest number from the Scene loaded from the game
Just as it showing i replicated the issue from the report but fixing it and showing the default game behavior
**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Shouldn't
(I've checked if in the config or in some way is changed but doesn't seem)
**Other information**:
The code is big and a mess because …
> `[EXILED::EVENTS]` Fixing bug report n.396

- Exiled.Events/EventArgs/Player/PreAuthenticatingEventArgs.cs
- Exiled.Events/Handlers/Player.cs
- Exiled.Events/Patches/Events/Player/PreAuthenticating.cs
Recoded PreAuthenticating event wia patch, so IsAllowed will work.
> Recoded Player.PreAuthenticating wia Patch

- Exiled.Events/EventArgs/Player/SendingCommandEventArgs.cs
- Exiled.Events/Exiled.Events.csproj
- Exiled.Events/Handlers/Player.cs
- Exiled.Events/Patches/Events/Player/SendingCommand.cs
> Added SendingCommand event
